/*
-------------------------------------------------------------------------------
-- DBRO 제품 테이블
-------------------------------------------------------------------------------
*/
CREATE TABLE EM_LOG (
    TRAN_PR             BIGINT          NOT NULL ,
    TRAN_REFKEY         VARCHAR(40),
    TRAN_ID             VARCHAR(20),
    TRAN_PHONE          VARCHAR(15)     NOT NULL ,
    TRAN_CALLBACK       VARCHAR(15),
    TRAN_STATUS         CHAR(1),
    TRAN_DATE           TIMESTAMP       NOT NULL ,
    TRAN_RSLTDATE       TIMESTAMP ,
    TRAN_REPORTDATE     TIMESTAMP ,
    TRAN_RSLT           CHAR(1),
    TRAN_NET            VARCHAR(3),
    TRAN_MSG            VARCHAR(255),
    TRAN_ETC1           VARCHAR(64),
    TRAN_ETC2           VARCHAR(16),
    TRAN_ETC3           VARCHAR(16),
    TRAN_ETC4           BIGINT ,
    TRAN_TYPE           INTEGER         NOT NULL
);

CREATE TABLE EM_TRAN (
    TRAN_PR             BIGINT          NOT NULL ,
    TRAN_REFKEY         VARCHAR(40),
    TRAN_ID             VARCHAR(20),
    TRAN_PHONE          VARCHAR(15)     NOT NULL ,
    TRAN_CALLBACK       VARCHAR(15),
    TRAN_STATUS         CHAR(1),
    TRAN_DATE           TIMESTAMP       NOT NULL ,
    TRAN_RSLTDATE       TIMESTAMP ,
    TRAN_REPORTDATE     TIMESTAMP ,
    TRAN_RSLT           CHAR(1),
    TRAN_NET            VARCHAR(3),
    TRAN_MSG            VARCHAR(255),
    TRAN_ETC1           VARCHAR(64),
    TRAN_ETC2           VARCHAR(16),
    TRAN_ETC3           VARCHAR(16),
    TRAN_ETC4           BIGINT ,
    TRAN_TYPE           INTEGER         NOT NULL
);
ALTER TABLE EM_TRAN ADD CONSTRAINT PK_TRAN_PR PRIMARY KEY (TRAN_PR);
CREATE INDEX IDX_EM_TRAN_01 ON EM_TRAN(TRAN_STATUS,TRAN_DATE);

CREATE TABLE EM_TRAN_MMS (
    MMS_SEQ             BIGINT          NOT NULL ,
    FILE_CNT            INTEGER         NOT NULL ,
    BUILD_YN            CHAR(1),
    MMS_BODY            VARCHAR(2000),
    MMS_SUBJECT         VARCHAR(40),
    FILE_TYPE1          VARCHAR(3),
    FILE_TYPE2          VARCHAR(3),
    FILE_TYPE3          VARCHAR(3),
    FILE_TYPE4          VARCHAR(3),
    FILE_TYPE5          VARCHAR(3),
    FILE_NAME1          VARCHAR(100),
    FILE_NAME2          VARCHAR(100),
    FILE_NAME3          VARCHAR(100),
    FILE_NAME4          VARCHAR(100),
    FILE_NAME5          VARCHAR(100),
    SERVICE_DEP1        VARCHAR(3),
    SERVICE_DEP2        VARCHAR(3),
    SERVICE_DEP3        VARCHAR(3),
    SERVICE_DEP4        VARCHAR(3),
    SERVICE_DEP5        VARCHAR(3),
    SKN_FILE_NAME       VARCHAR(255)
);

/*
-------------------------------------------------------------------------------
-- WISEU 연동
-------------------------------------------------------------------------------
*/
ALTER TABLE EM_LOG     ADD REQ_DEPT_CD    VARCHAR(20);
ALTER TABLE EM_LOG     ADD SERVICE_TYPE   CHAR(2);
ALTER TABLE EM_LOG     ADD SERVICE_NO     DECIMAL(15);
ALTER TABLE EM_LOG     ADD RESULT_SEQ     DECIMAL(16);
ALTER TABLE EM_LOG     ADD SEQ            VARCHAR(100);
ALTER TABLE EM_LOG     ADD SVC_ID         VARCHAR(20);
ALTER TABLE EM_LOG     ADD SLOT1          VARCHAR(100);
ALTER TABLE EM_LOG     ADD SLOT2          VARCHAR(100);
ALTER TABLE EM_LOG     ADD REQ_USER_ID    VARCHAR(100);
ALTER TABLE EM_LOG     ADD REQ_DEPT_ID    VARCHAR(50);
ALTER TABLE EM_LOG     ADD LIST_SEQ       VARCHAR(10);

ALTER TABLE EM_TRAN    ADD REQ_DEPT_CD    VARCHAR(20)     DEFAULT '#admin';
ALTER TABLE EM_TRAN    ADD SERVICE_TYPE   CHAR(2);
ALTER TABLE EM_TRAN    ADD SERVICE_NO     DECIMAL(15);
ALTER TABLE EM_TRAN    ADD RESULT_SEQ     DECIMAL(16);
ALTER TABLE EM_TRAN    ADD SEQ            VARCHAR(100);
ALTER TABLE EM_TRAN    ADD SVC_ID         VARCHAR(20);
ALTER TABLE EM_TRAN    ADD SLOT1          VARCHAR(100);
ALTER TABLE EM_TRAN    ADD SLOT2          VARCHAR(100);
ALTER TABLE EM_TRAN    ADD REQ_USER_ID    VARCHAR(100);
ALTER TABLE EM_TRAN    ADD REQ_DEPT_ID    VARCHAR(50);
ALTER TABLE EM_TRAN    ADD LIST_SEQ       VARCHAR(10);

-- wiseMOKA 기능 개발 과정에 추가
ALTER TABLE EM_TRAN_MMS    ADD    LIST_SEQ           VARCHAR(10);
ALTER TABLE EM_TRAN_MMS    ADD    RESULT_SEQ         NUMERIC(16);
ALTER TABLE EM_TRAN_MMS    ADD    RESULT_SEQ_PAGE    NUMERIC(5);

CREATE INDEX IDX_EM_TRAN_MMS_RSLT ON EM_TRAN_MMS (RESULT_SEQ, RESULT_SEQ_PAGE);

-- EM_LOG 테이블의 발송 결과를 wiseU NVSENDLOG, NVECARESENDLOG 테이블에 업데이트하는 작업 플래그
ALTER TABLE EM_LOG ADD SYNC_FLAG CHAR(1) DEFAULT 'N' NOT NULL;
CREATE INDEX IDX_EM_LOG_SYNC_FLAG ON EM_LOG (SYNC_FLAG);

-- WISEU 연동 기본 컬럼
-- SMS/LMS/MMS 재발송 시 사용
CREATE INDEX IDX_EMLOG_SRLS ON EM_LOG (SERVICE_NO, RESULT_SEQ, LIST_SEQ, SERVICE_TYPE);
CREATE INDEX IDX_EMLOG_TDT ON EM_LOG (TRAN_DATE);
