-- SMS 리포트 전송 성공자 다운로드
CREATE VIEW V_SMS_SUCCESS_FILE_LOG (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
) AS
SELECT
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_ETC3 AS TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
FROM EM_LOG
WHERE TRAN_RSLT IN ('0', '00000');

-- SMS 리포트 전송 실패자 다운로드
CREATE VIEW V_SMS_FAIL_FILE_LOG (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
) AS
SELECT
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_ETC3 AS TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
FROM EM_LOG
WHERE TRAN_RSLT NOT IN ('0', '00000');

-- SMS 리포트 오류 분석 리스트
CREATE VIEW V_SMS_ERROR_RESULT (
    TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ, SEQ, LIST_SEQ
) AS
SELECT
    TO_CHAR(TRAN_DATE,'YYYYMMDD') TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ, SEQ, LIST_SEQ
FROM EM_LOG
WHERE TRAN_RSLT NOT IN ('0', '00000');

-- 연동 쪽에서 SMS 결과를 조회하는 용도 (NVREALTIMEACCEPT를 통한 준실시간 연동에서 사용)
CREATE VIEW VIEW_SMS_LOG (
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, TRAN_RSLT,
    TRAN_MSG, SMS_TYPE, SLOT1, SLOT2, SEQ, LIST_SEQ
) AS
SELECT
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, TRAN_RSLT,
    (CASE WHEN MMS_BODY IS NULL THEN TRAN_MSG ELSE MMS_BODY END) AS TRAN_MSG, TRAN_ETC3 AS SMS_TYPE, SLOT1, SLOT2, SEQ, LOG.LIST_SEQ
FROM EM_LOG LOG LEFT OUTER JOIN EM_TRAN_MMS MMS
ON LOG.TRAN_ETC4 = MMS.MMS_SEQ;