-- 캠페인도메인별발송로그
CREATE TABLE NVDOMAINLOG (
    CAMPAIGN_NO               NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    DOMAIN_NM                 VARCHAR(50)         NOT NULL,
    ERROR_CD                  VARCHAR(4)          NOT NULL,
    SEND_CNT                  NUMERIC(10)
);
ALTER TABLE NVDOMAINLOG ADD CONSTRAINT PK_NVDOMAINLOG PRIMARY KEY (CAMPAIGN_NO, RESULT_SEQ, DOMAIN_NM, ERROR_CD);

-- 캠페인유효수신통계
CREATE TABLE NVRPTDURATION (
    CAMPAIGN_NO               NUMERIC(15)         NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    DURATIONINFO_CD           CHAR(2),
    VALIDOPEN_CNT             NUMERIC(10),
    VALIDOPEN_OCNT            NUMERIC(10),
    RESULT_SEQ                NUMERIC(16)         NOT NULL
);
ALTER TABLE NVRPTDURATION ADD CONSTRAINT PK_NVRPTDURATION PRIMARY KEY (CAMPAIGN_NO, RESULT_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVRPTDURATION_REPORT_DT ON NVRPTDURATION (REPORT_DT);

-- 캠페인링크클릭통계
CREATE TABLE NVRPTLINK (
    CAMPAIGN_NO               NUMERIC(15)         NOT NULL,
    LINK_SEQ                  NUMERIC(3)          NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    LINK_CNT                  NUMERIC(10),
    LINK_OCNT                 NUMERIC(10),
    RESULT_SEQ                NUMERIC(16)         NOT NULL
);
ALTER TABLE NVRPTLINK ADD CONSTRAINT PK_NVRPTLINK PRIMARY KEY (CAMPAIGN_NO, RESULT_SEQ, LINK_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVRPTLINK_RDT_CNO ON NVRPTLINK (REPORT_DT, CAMPAIGN_NO);

-- 캠페인링크클릭비중복통계
CREATE TABLE NVRPTLINKDISTINCT (
    CAMPAIGN_NO               NUMERIC(15)         NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    LINK_CNT                  NUMERIC(10),
    LINK_OCNT                 NUMERIC(10),
    RESULT_SEQ                NUMERIC(16)         NOT NULL
);
ALTER TABLE NVRPTLINKDISTINCT ADD CONSTRAINT PK_NVRPTLINKDISTINCT PRIMARY KEY (CAMPAIGN_NO, RESULT_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVRPTLINKDISTINCT_RPT_DT ON NVRPTLINKDISTINCT (REPORT_DT);

-- 캠페인수신확인통계
CREATE TABLE NVRPTOPEN (
    CAMPAIGN_NO               NUMERIC(15)         NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    OPEN_CNT                  NUMERIC(10),
    REFUSE_CNT                NUMERIC(10),
    OPEN_OCNT                 NUMERIC(10),
    RESULT_SEQ                NUMERIC(16)         NOT NULL
);
ALTER TABLE NVRPTOPEN ADD CONSTRAINT PK_NVRPTOPEN PRIMARY KEY (CAMPAIGN_NO, RESULT_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVRPTOPEN_REPORT_DT ON NVRPTOPEN (REPORT_DT);

-- 이케어도메인별발송로그
CREATE TABLE NVECAREDOMAINLOG (
    ECARE_NO                  NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    DOMAIN_NM                 VARCHAR(50)         NOT NULL,
    ERROR_CD                  VARCHAR(4)          NOT NULL,
    SEND_DT                   CHAR(8)             NOT NULL,
    SEND_CNT                  NUMERIC(10)         NOT NULL
);
ALTER TABLE NVECAREDOMAINLOG ADD CONSTRAINT PK_NVECAREDOMAINLOG PRIMARY KEY (ECARE_NO, RESULT_SEQ, DOMAIN_NM, ERROR_CD, SEND_DT);
CREATE INDEX IDX_NVECAREDOMAINLOG_SDT_ENO ON NVECAREDOMAINLOG (SEND_DT, ECARE_NO);

-- 이케어링크클릭통계
CREATE TABLE NVECARERPTLINK (
    ECARE_NO                  NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    LINK_SEQ                  NUMERIC(2)          NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    LINK_CNT                  NUMERIC(10),
    LINK_OCNT                 NUMERIC(10)
);
ALTER TABLE NVECARERPTLINK ADD CONSTRAINT PK_NVECARERPTLINK PRIMARY KEY (ECARE_NO, RESULT_SEQ, LINK_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVECARERPTLINK_RDT_ENO ON NVECARERPTLINK (REPORT_DT, ECARE_NO);

-- 이케어수신확인통계
CREATE TABLE NVECARERPTOPEN (
    ECARE_NO                  NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    START_DT                  CHAR(8)             NOT NULL,
    OPEN_CNT                  NUMERIC(10),
    REFUSE_CNT                NUMERIC(10),
    OPEN_OCNT                 NUMERIC(10),
    OPEN_DCNT                 NUMERIC(10)
);
ALTER TABLE NVECARERPTOPEN ADD CONSTRAINT PK_NVECARERPTOPEN PRIMARY KEY (ECARE_NO, RESULT_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVECARERPTOPEN_RDT_ENO ON NVECARERPTOPEN (REPORT_DT, ECARE_NO);
CREATE INDEX IDX_NVECARERPTOPEN_SDT_ENO ON  NVECARERPTOPEN (START_DT,ECARE_NO);

-- 이케어발송결과통계
CREATE TABLE NVECARERPTSENDRESULT (
    ECARE_NO                  NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    RESULT_DESC               VARCHAR(250),
    RESULT_STS                CHAR(2),
    TARGET_CNT                NUMERIC(10),
    SEND_CNT                  NUMERIC(10),
    SUCCESS_CNT               NUMERIC(10),
    FAIL_CNT                  NUMERIC(10),
    UNKNOWN_USER_CNT          NUMERIC(10),
    UNKNOWN_HOST_CNT          NUMERIC(10),
    SMTP_EXCEPT_CNT           NUMERIC(10),
    NO_ROUTE_CNT              NUMERIC(10),
    REFUSED_CNT               NUMERIC(10),
    ETC_EXCEPT_CNT            NUMERIC(10),
    INVALID_ADDRESS_CNT       NUMERIC(10),
    LOG_STS                   CHAR(2),
    RETURNMAIL_CNT            NUMERIC(10)         DEFAULT 0,
    OPEN_CNT                  NUMERIC(10)         DEFAULT 0,
    DURATION_CNT              NUMERIC(10)         DEFAULT 0,
    LINK_CNT                  NUMERIC(10)         DEFAULT 0,
    START_DT                  VARCHAR(8),
    START_TM                  VARCHAR(6),
    END_DT                    VARCHAR(8),
    END_TM                    VARCHAR(6),
    RESEND_STS                CHAR(1)
);
ALTER TABLE NVECARERPTSENDRESULT ADD CONSTRAINT PK_NVECARERPTSENDRESULT PRIMARY KEY (ECARE_NO, RESULT_SEQ, REPORT_DT);
CREATE INDEX IDX_NVECARERPTSENDRESULT_MLT1 ON NVECARERPTSENDRESULT (REPORT_DT, ECARE_NO);

-- 이케어유효수신통계
CREATE TABLE NVECARERPTDURATION (
    ECARE_NO                  NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    REPORT_DT                 CHAR(8)             NOT NULL,
    REPORT_TM                 CHAR(2)             NOT NULL,
    DURATIONINFO_CD           CHAR(2),
    VALIDOPEN_CNT             NUMERIC(10),
    VALIDOPEN_OCNT            NUMERIC(10)
);
ALTER TABLE NVECARERPTDURATION ADD CONSTRAINT PK_NVECARERPTDURATION PRIMARY KEY (ECARE_NO, RESULT_SEQ, REPORT_DT, REPORT_TM);
CREATE INDEX IDX_NVECARERPTDURATION_RDT_ENO ON NVECARERPTDURATION (REPORT_DT, ECARE_NO);

-- SMS발송결과통계
CREATE TABLE NVSMSRPTSENDRESULT (
    REPORT_DT                 CHAR(8)             NOT NULL,
    SERVICE_NO                NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    SERVICE_TYPE              CHAR(2)             NOT NULL,
    TARGET_CNT                NUMERIC(10),
    SEND_CNT                  NUMERIC(10),
    SUCCESS_CNT               NUMERIC(10),
    FAIL_CNT                  NUMERIC(10),
    SEND_GBN                  VARCHAR(3)          NOT NULL,
    SEND_TM                   CHAR(6)             NOT NULL
);
ALTER TABLE NVSMSRPTSENDRESULT ADD CONSTRAINT PK_NVSMSRPTSENDRESULT PRIMARY KEY (REPORT_DT, SERVICE_NO, RESULT_SEQ, SERVICE_TYPE, SEND_GBN);
CREATE INDEX IDX_NVSMSRPTSENDRESULT_SNO_SGB ON NVSMSRPTSENDRESULT (SERVICE_NO, SEND_GBN);
CREATE INDEX IDX_NVSMSRPTSENDRESULT_SNO_RSQ ON NVSMSRPTSENDRESULT (SERVICE_NO, RESULT_SEQ);
CREATE INDEX IDX_NVSMSRPTSENDRESULT_SNO_STP ON NVSMSRPTSENDRESULT (SERVICE_NO, SERVICE_TYPE);

-- 알림톡/친구톡 발송통계
CREATE TABLE NVKAKAORPTSENDRESULT(
    REPORT_DT                 CHAR(8)             NOT NULL,
    SERVICE_NO                NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    SERVICE_TYPE              CHAR(2)             NOT NULL,
    REQ_DEPT_ID               VARCHAR(50)         NOT NULL,
    TMPL_CD                   VARCHAR(50)         DEFAULT 'FT'    NOT NULL,
    TARGET_CNT                NUMERIC(10),
    SEND_CNT                  NUMERIC(10),
    SUCCESS_CNT               NUMERIC(10),
    FAIL_CNT                  NUMERIC(10),
    SMS_TARGET_CNT            NUMERIC(10),
    SMS_SEND_CNT              NUMERIC(10),
    SMS_SUCCESS_CNT           NUMERIC(10),
    SMS_FAIL_CNT              NUMERIC(10),
    LMS_TARGET_CNT            NUMERIC(10),
    LMS_SEND_CNT              NUMERIC(10),
    LMS_SUCCESS_CNT           NUMERIC(10),
    LMS_FAIL_CNT              NUMERIC(10),
    MMS_TARGET_CNT            NUMERIC(10),
    MMS_SEND_CNT              NUMERIC(10),
    MMS_SUCCESS_CNT           NUMERIC(10),
    MMS_FAIL_CNT              NUMERIC(10),
    SEND_GBN                  VARCHAR(3)          NOT NULL,
    SEND_TM                   CHAR(6)             NOT NULL
);
ALTER TABLE NVKAKAORPTSENDRESULT ADD CONSTRAINT PK_NVKAKAORPTSENDRESULT PRIMARY KEY (REPORT_DT, SERVICE_NO, RESULT_SEQ, SERVICE_TYPE,REQ_DEPT_ID, TMPL_CD);
CREATE INDEX IDX_NVKAKAKORPT_SNO_SGB ON NVKAKAORPTSENDRESULT (SERVICE_NO, SEND_GBN);
CREATE INDEX IDX_NVKAKAKORPT_SNO_RSQ ON NVKAKAORPTSENDRESULT (SERVICE_NO, RESULT_SEQ);
CREATE INDEX IDX_NVKAKAKORPT_SNO_STP ON NVKAKAORPTSENDRESULT (SERVICE_NO, SERVICE_TYPE);