CREATE VIEW V_ECARERPTSENDRESULT (
    ECARE_NO, ACCU_CNT, SERVICE_TYPE, REPORT_DT, TARGET_CNT, SEND_CNT, SUCCESS_CNT,
    SOFT_BOUNCE_CNT, HARD_BOUNCE_CNT, RETURNMAIL_CNT, OPEN_CNT, DURATION_CNT, LINK_CNT
) AS
SELECT
    ECARE_NO,
    COUNT(ECARE_NO) AS ACCU_CNT,
    (CASE MAX(RESULT_SEQ) WHEN 1 THEN 'R' ELSE 'S' END) AS SERVICE_TYPE,
    MAX(REPORT_DT) AS REPORT_DT,
    SUM(TARGET_CNT) AS TARGET_CNT,
    SUM(SEND_CNT) AS SEND_CNT,
    SUM(SUCCESS_CNT) AS SUCCESS_CNT,
    SUM(SMTP_EXCEPT_CNT + NO_ROUTE_CNT + REFUSED_CNT + ETC_EXCEPT_CNT) AS SOFT_BOUNCE_CNT,
    SUM(UNKNOWN_USER_CNT + UNKNOWN_HOST_CNT + INVALID_ADDRESS_CNT) AS HARD_BOUNCE_CNT,
    SUM(RETURNMAIL_CNT) AS RETURNMAIL_CNT,
    SUM(OPEN_CNT) AS OPEN_CNT,
    SUM(DURATION_CNT) AS DURATION_CNT,
    SUM(LINK_CNT) AS LINK_CNT
FROM NVECARERPTSENDRESULT
GROUP BY ECARE_NO;

CREATE VIEW V_NVTESTUSER (
    USER_ID, SEQ_NO, CAMPAIGN_NO, CAMPAIGN_TYPE,
    TESTRECEIVER_EMAIL, TESTRECEIVER_TEL, TESTRECEIVER_FAX, TESTRECEIVER_NM
) AS
SELECT
    U.USER_ID, U.SEQ_NO, U.CAMPAIGN_NO, U.CAMPAIGN_TYPE,
    P.TESTRECEIVER_EMAIL, P.TESTRECEIVER_TEL, P.TESTRECEIVER_FAX, P.TESTRECEIVER_NM
FROM NVTESTUSER U, NVTESTUSERPOOL P
WHERE U.USER_ID = P.USER_ID
AND U.SEQ_NO = P.SEQ_NO;