-- 메뉴다국어
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('01','vn','Campaign');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0714','vn','Quản lý Đăng nhập');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0103','vn','Đăng ký campaign');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0104','vn','Hồ sơ cá nhân campaign');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('02','vn','ECARE');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0201','vn','Danh sách ECARE');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0202','vn','Đăng ký ECARE');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0203','vn','Hồ sơ cá nhân ECARE');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0204','vn','thay cầu content');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('03','vn','Báo cáo');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030105','vn','Phân tích So sánh');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030101','vn','Danh sách campaign');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030106','vn','Báo cáo hàng tháng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030107','vn','Thống kê thanh toán của cục');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030201','vn','Danh sách ECARE');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030203','vn','Báo cáo hàng tháng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030204','vn','Thống kê thanh toán của cục');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0303','vn','Hồ sơ cá nhân');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('030301','vn','Chế độ xem khách hàng/Gửi lại');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('04','vn','Template');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0401','vn','Danh sách Template');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0402','vn','Đăng ký Template');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0403','vn','Danh sách Template mobile');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0404','vn','Đăng ký Template mobile');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('05','vn','đối tượng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0501','vn','Xem đối tượng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0502','vn','Đăng ký đối tượng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0504','vn','Tải file lên đối tượng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('06','vn','người sử dụng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0601','vn','Quản lý người sử dụng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0602','vn','Quản lý quyền');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0603','vn','Session Log');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0604','vn','Admin Log');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0606','vn','Quản lý Bộ phận');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0607','vn','Quản lý người sử dụng');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0608','vn','Quản lý quyền Bộ phận');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('07','vn','Cài đặt môi trường');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0701','vn','Thông tin môi trường máy chủ');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0702','vn','Quản lý DB');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0703','vn','Quản lý Ngày lễ');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0704','vn','Tên miền');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0705','vn','Từ bị cấm');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0706','vn','Quản lý Tương tác Dịch vụ');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0707','vn','Cài đặt trình xử lý cơ bản');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0708','vn','Cài đặt Xử lý hàng loạt');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0710','vn','Quản lý Mã');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0711','vn','Thông tin tin Người gửi nhắn');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0712','vn','Quản lý Thông tin cá nhân');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0713','vn','Quản lý lịch sử ECARE');
INSERT INTO NVMENU_LANG ( MENU_CD, LANG, MENU_NM)
VALUES ('0715', 'vn', 'PUSH Setting');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES('0102','vn','Danh sách campaign');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES ('0407', 'vn', 'Brandtalk Lists');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES ('0408', 'vn', 'Create Brandtalk');

-- 코드마스터
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C000','-','00','Mã phổ biến','Mã phổ biến Được sử dụng bởi tất cả các chương trình ',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C0001','-','C000','Soft bounce mã lỗi mail','Soft bounce mã lỗi mail','err_cd','y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00001','250','C0001','Gửi thành công','Gửi thành công',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','421','C0001','Không thể sử dụng dịchVụ (Vấn đề hệ thống của SMTP đối phương)','Không thể sử dụng dịchVụ (Vấn đề hệ thống của SMTP đối phương)',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','450','C0001','Trạng thái hòm thư bị khóa','Trạng thái hòm thư bị khóa',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','451','C0001','Lỗi server (Vấn đề hệ thống của SMTP đối phương)','Lỗi server (Vấn đề hệ thống của SMTP đối phương)',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','452','C0001','Không gian lưu của hệ thống bị thiếu','Không gian lưu của hệ thống bị thiếu',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','552','C0001','ĐãVượt quá dung lượng hộp thư','ĐãVượt quá dung lượng hộp thư',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','554','C0001','Giao dịch thất bại','Giao dịch thất bại',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','600','C0001','Host bị bận hoặc không cung cấp dịchVụ ở cổng được yêu cầu','Host bị bận hoặc không cung cấp dịchVụ ở cổng được yêu cầu',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','601','C0001','Vượt quá thời gian kết nối','Vượt quá thời gian kết nối',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','602','C0001','Connection Failure','Connection Failure',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','603','C0001','Connection Error','Connection Error',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','604','C0001','Phát sinh IOException hoặc mất kết nối trong khi chờ câu trả lời  ','Phát sinh IOException hoặc mất kết nối trong khi chờ câu trả lời  ',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','700','C0001','Mất kết nối trong khi giao tiếp','Mất kết nối trong khi giao tiếp',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','701','C0001','IOException','IOException',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','702','C0001','Chiều dài của mã trả lời dưới 3','Chiều dài của mã trả lời dưới 3',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','703','C0001','IOException trong khi chờ mã trả lời hoặc truyền câu lệnh','IOException trong khi chờ mã trả lời hoặc truyền câu lệnh',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','704','C0001','SMTP Time out','SMTP Time out',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','888','C0001','Trường hợp khác','Trường hợp khác',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00011','999','C0001','Người dùng đã bị từ chối nhận','Người dùng đã bị từ chối nhận',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C0002','-','C000','Hard bounce mã lỗi mail','Hard bounce mã lỗi mail','err_cd','y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00021','550','C0002','Không có người sử dụng','Không có người sử dụng',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00021','553','C0002','Câu lệnh bị dừng do tên hòm thư không hợp lệ','Câu lệnh bị dừng do tên hòm thư không hợp lệ',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00021','610','C0002','Unknown Host','Unknown Host',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00021','800','C0002','Invalid Address','Invalid Address',NULL,'y','20180302160040',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C0006','-','C000','Quyền người sử dụng','Quyền người sử dụng','usertype_cd','y','20180302160041',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00061','A','C0006','ADMIN','Quản lý',NULL,'y','20180302160041',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00061','M','C0006','MANAGER','Quản lý',NULL,'y','20180302160041',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00061','U','C0006','USER','Người sử dụng',NULL,'y','20180302160041',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA001','-','00','Mẫu thông báo','Mẫu thông báo Mã liên quan',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA011','REG','KA01','Đăng ký','Đăng ký',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA011','REQ','KA01','Yêu cầu kiểm tra','Yêu cầu kiểm tra',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA011','APR','KA01','Phê duyệt','Phê duyệt',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA011','REJ','KA01','Trả lại','Trả lại',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA012','S','KA01','Gián đoạn','Gián đoạn',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA012','A','KA01','Bình thường','Bình thường',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA012','R','KA01','Chờ','Chờ',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA013','INQ','KA01','Câu hỏi','Câu hỏi',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA013','REP','KA01','Trả lời','Trả lời',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA013','APR','KA01','Phê duyệt','Phê duyệt',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('KA013','REJ','KA01','Trả lại','Trả lại',NULL,'y','20180306113940',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AA00','-','00','Thông báo phổ biến','Mã lỗi được sử dụng trong thông báo',NULL,'y','20180302160219',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AA0001','0000','AA00','Mã thông thường','Truyền / tiếp nhận thành công khi response method là realtime, polling/callback thành công trongViệc gửi',NULL,'y','20180302160219',NULL,1,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('00','-','-','Mã nguồn chung','Mã phổ biến',NULL,'y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('1001','-','00','Liên quan đến campaign','Mã liên quan campaign',NULL,'y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('10011','-','1001','Trạng thái thực hiện campaign',NULL,'campaign_sts','y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','1','10011','Lỗi','select_schedule Ở giữa',NULL,'y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','2','10011','Lỗi','make_target Ở giữa',NULL,'y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','3','10011','Lỗi','mas_send Ở giữa',NULL,'y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','A','10011','Phê duyệt','FormatUtil.java Tham chiếu tệp',NULL,'y','20180302160036',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','C','10011','Đề nghị phê duyệt','Đề nghị phê duyệt',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','D','10011','Từ chối phê duyệt','FormatUtil.java Thêm theo tham chiếu tập tin',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','E','10011','Đã gửi','Đã gửi',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','I','10011','Đang làm','Đang làm',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','O','10011','Lỗi gửi','FormatUtil.java Thêm theo tham chiếu tập tin',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','P','10011','Bảo lưu','Bảo lưu',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','R','10011','Chờ gửi','Chờ gửi',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','S','10011','Tạm dừng','Tạm dừng',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','T','10011','Ngừng gửi','Ngừng gửi',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','V','10011','Dừng phân chia','Dừng phân chia',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100111','W','10011','Đang gửi','Đang gửi',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('10012','-','1001','Trạng thái thực hiện eBasic',NULL,'campaign_sts','y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','A','10012','Đã phê duyệt','Đã phê duyệt',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','C','10012','Đề nghị phê duyệt','Đề nghị phê duyệt',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','D','10012','Từ chối phê duyệt','Từ chối phê duyệt',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','E','10012','Đã gửi','Đã gửi',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','I','10012','Đang làm','Đang làm',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','O','10012','Lỗi gửi','Lỗi gửi (Cần điều tra)',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100121','R','10012','Chuẩn bị','Chuẩn bị',NULL,'y','20180302160037',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('10020','-','1001','Trạng thái tiến hành',NULL,'result_sts','y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','MS','10020','Bắt đầu làmViệc MAS','Bắt đầu làmViệc MAS(Khi sử dụng máy chủ 3.0)',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','LW','10020','Đang tiến hành','Đang tiến hành(Khi sử dụng máy chủ 3.0)',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','SE','10020','Kết thúc','Kết thúc(Khi sử dụng máy chủ 3.0)',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','XE','10020','Đã gửi','Đã gửi',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','XO','10020','Lỗi','Lỗi',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','XR','10020','Đang chuẩn bị','Đang chuẩn bị',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','XS','10020','Tạm dừng','Tạm dừng',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','XT','10020','Dừng','Dừng',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100201','XW','10020','Đang làmViệc','Đang làmViệc',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('10022','-','1001','Loại kênh gửi','Loại kênh gửi','relation_type','y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100221','L','10022','Phản ứng','Phản ứng',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100221','N','10022','Chung','Chung gửi',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100221','R','10022','Gửi lại','Gửi lại',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100221', 'S', '10022', 'Success', 'Success', NULL, 'y','20180302160038', NULL, NULL, 'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100221', 'F', '10022', 'Fail', 'Fail', NULL, 'y','20180302160038', NULL, NULL, 'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100221', 'O', '10022', 'Open', 'Open', NULL, 'y','20180302160038', NULL, NULL, 'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('2001','-','00','Liên quan đến ECARE','Liên quan đến ECARE Code',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('20011','-','2001','Trạng thái thực hiện ECARE','Trạng thái thực hiện ECARE','ecare_sts','y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200111','I','20011','Đang làm','Đang làm',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200111','P','20011','Dừng','Dừng',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200111','R','20011','Thực hiện','Thực hiện',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200111','S','20011','Tạm dừng','Tạm dừng',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200111','T','20011','Đang kiểm tra','Đang kiểm tra',NULL,'y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('20013','-','2001','Loại dịchVụ ECARE','Loại dịchVụ ECARE','service_type','y','20180302160038',NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200131','SN','20013','Gần thời gian thực','Gần thời gian thực',NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200131','SR','20013','Schedule (phút)','Schedule (phút)',NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200131','SS','20013','Schedule','Schedule',NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('20014','-','2001','ECARE Schedule Subtype','ECARE Schedule Subtype','sub_type','y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200141','N','20014','Gần thời gian thực','Gần thời gian thực',NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200141','R','20014','Schedule (phút)','Schedule (phút)',NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('200141','S','20014','Schedule','Schedule',NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT,VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('4001','-','00','Liên quan đến báo cáo',NULL,NULL,'y',TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'),NULL,NULL,'vn');

-- 메일발송결과카테고리
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('01', '03', NULL, 0, 'SMTP', 'SMTP Category', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0101', '03', '01', 1, 'Unknown User', 'Unknown User Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0102', '03', '01', 1, 'Unknown Host', 'Unknown Host Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0103', '03', '01', 1, 'SMTP Exception', 'SMTP Exception Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0104', '03', '01', 1, 'NoRoute To Host', 'NoRoute To Host Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0105', '03', '01', 1, 'Connection Refused', 'Connection Refused Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0106', '03', '01', 1, 'Exception', 'Exception Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0107', '03', '01', 1, 'Invalid Address', 'Invalid Address Group', 'Y');
INSERT INTO NVSMTPCATEGORY(CATEGORY_CD, GRP_CD, PCATEGORY_CD, LEVEL_CD, CATEGORY_NM, CATEGORY_DESC, ACTIVE_YN)
VALUES('0108', '03', '01', 1, 'Receive Rejection', 'Receive Rejection', 'Y');

-- 메일발송결과코드
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('250',NULL,'Gửi thành công',NULL,'01','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('421',NULL,'Không thể sử dụng dịch vụ (Vấn đề hệ thống của SMTP đối phương)',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('450',NULL,'Trạng thái hòm thư bị khóa',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('451',NULL,'Lỗi server (Vấn đề hệ thống của SMTP đối phương)',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('452',NULL,'Không gian lưu của hệ thống bị thiếu',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('550',NULL,'Không có người sử dụng',NULL,'0101','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('552',NULL,'Đã vượt quá dung lượng hộp thư',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('553',NULL,'Câu lệnh bị dừng do tên hòm thư không hợp lệ',NULL,'0101','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('554',NULL,'Giao dịch thất bại',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('600',NULL,'Host bị bận hoặc không cung cấp dịch vụ ở cổng được yêu cầu',NULL,'0105','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('601',NULL,'Vượt quá thời gian kết nối',NULL,'0104','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('602',NULL,'Connection Failure',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('610',NULL,'Unknown Host',NULL,'0102','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('603',NULL,'Connection Error',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('604',NULL,'Phát sinh IOException hoặc mất kết nối trong khi chờ câu trả lời  ',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('700',NULL,'Mất kết nối trong khi giao tiếp',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('701',NULL,'IOExcepition',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('702',NULL,'Chiều dài của mã trả lời dưới 3',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('703',NULL,'IOException trong khi chờ mã trả lời hoặc truyền câu lệnh',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('704',NULL,'SMTP TIME OUT',NULL,'0103','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('800',NULL,'Invalid Address',NULL,'0107','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('888',NULL,'Trường hợp khác',NULL,'0106','M','N');
INSERT INTO NVSENDERR(ERROR_CD, ERROR_NM, ERROR_DESC, CATEGORY_CD, CHANNEL_TYPE)
VALUES('999',NULL,'Người dùng đã bị từ chối nhận',NULL,'0107','M','N');

-- 발송주기
INSERT INTO NVSENDCYCLE(CYCLE_CD, CYCLE_NM) VALUES ('1', '매일');
INSERT INTO NVSENDCYCLE(CYCLE_CD, CYCLE_NM) VALUES ('2', '매주');
INSERT INTO NVSENDCYCLE(CYCLE_CD, CYCLE_NM) VALUES ('3', '매월');
INSERT INTO NVSENDCYCLE(CYCLE_CD, CYCLE_NM) VALUES ('4', '한번만');
INSERT INTO NVSENDCYCLE(CYCLE_CD, CYCLE_NM) VALUES ('5', '분단위');

-- 사용자그룹[부서]
INSERT INTO NVUSERGRP (GRP_CD, GRP_NM, SUPRAGRP_CD, GRP_DESC, GRP_LEVEL, PERMISSION, EDITOR_ID, LASTUPDATE_DT, MANAGER_ID, ACTIVE_YN, ETC_INFO1, MANAGER_NM)
VALUES('01', 'mnwise', NULL, '최상위 부서', 0, 'Y', 'admin', DATE_FORMAT(NOW(); '%Y%m%d'); 'manager', 'Y', NULL, '최상위부서장');

-- 사용자
-- 관리자
-- 암호화 :
-- PASS_WD = '5b55082cc30ad7b892f7c459dcbeb6e7665e54de6efdd505edc09c195ef7571a',
-- PASS_SALT = '2664acd0628a78afe656';
-- 복호화 : 1111
-- INSERT INTO NVUSER (USER_ID, PASS_WD, PASS_SALT, GRP_CD, NAME_KOR, NAME_ENG, TEL_NO, EMAIL, USER_CLASS, USERTYPE_CD, LASTUPDATE_DT, ACTIVE_YN, ACCEPT_YN, USER_ROLE)
-- VALUES('admin', '5b55082cc30ad7b892f7c459dcbeb6e7665e54de6efdd505edc09c195ef7571a', '2664acd0628a78afe656', '01', '시스템관리자', 'Administrator', '02-3445-0922', 'admin@mnwise.com', '관리자', 'A', DATE_FORMAT(NOW(); '%Y%m%d'); 'Y', 'Y', 'A');
-- 최상위 부서장 등록
-- INSERT INTO NVUSER (USER_ID, PASS_WD, PASS_SALT, GRP_CD, NAME_KOR, NAME_ENG, TEL_NO, EMAIL, USER_CLASS, USERTYPE_CD, LASTUPDATE_DT, ACTIVE_YN, ACCEPT_YN)
-- VALUES('manager', '5b55082cc30ad7b892f7c459dcbeb6e7665e54de6efdd505edc09c195ef7571a', '2664acd0628a78afe656', '01', '최상위 부서장', 'Manager', '02-3445-0922', 'manager@mnwise.com', '최상위부서장', 'M', DATE_FORMAT(NOW(); '%Y%m%d'); 'Y', 'Y');
-- TEST유져 등록
-- INSERT INTO NVUSER (USER_ID, PASS_WD, PASS_SALT, GRP_CD, NAME_KOR, NAME_ENG, TEL_NO, EMAIL, USER_CLASS, USERTYPE_CD, LASTUPDATE_DT, ACTIVE_YN, ACCEPT_YN)
-- VALUES('test', '5b55082cc30ad7b892f7c459dcbeb6e7665e54de6efdd505edc09c195ef7571a', '2664acd0628a78afe656', '01', '테스터', 'User', '02-3445-0922', 'test@mnwise.com', '테스터', 'U', DATE_FORMAT(NOW(); '%Y%m%d'); 'Y', 'Y');

-- 사용자
INSERT INTO NVUSER (USER_ID, PASS_WD, GRP_CD, NAME_KOR, NAME_ENG, TEL_NO, EMAIL, USER_CLASS, USERTYPE_CD, LASTUPDATE_DT, ACTIVE_YN, ACCEPT_YN, USER_ROLE)
VALUES('admin', '1111', '01', 'Quản trị hệ thống', 'Administrator', '02-3445-0922', 'admin@mnwise.com', 'Quản trị hệ thống', 'A', DATE_FORMAT(NOW(); '%Y%m%d'); 'Y', 'Y', 'A');
-- 최상위 부서장 등록
INSERT INTO NVUSER (USER_ID, PASS_WD, GRP_CD, NAME_KOR, NAME_ENG, TEL_NO, EMAIL, USER_CLASS, USERTYPE_CD, LASTUPDATE_DT, ACTIVE_YN, ACCEPT_YN)
VALUES('manager', '1111', '01', 'Đầu cấp cao', 'Manager', '02-3445-0922', 'manager@mnwise.com', 'Đầu cấp cao', 'M', DATE_FORMAT(NOW(); '%Y%m%d'); 'Y', 'Y');
-- TEST유져 등록
INSERT INTO NVUSER (USER_ID, PASS_WD, GRP_CD, NAME_KOR, NAME_ENG, TEL_NO, EMAIL, USER_CLASS, USERTYPE_CD, LASTUPDATE_DT, ACTIVE_YN, ACCEPT_YN)
VALUES('test', '1111', '01', 'Người kiểm tra', 'User', '02-3445-0922', 'test@mnwise.com', 'Người kiểm tra', 'U', DATE_FORMAT(NOW(); '%Y%m%d'); 'Y', 'Y');


-- 대상자DB접속정보
INSERT INTO NVDBINFO(DBINFO_SEQ, DRIVER_NM) VALUES(1, '임시DB정보');

-- 이케어 준실시간 옴니채널용 기준 세그먼트
INSERT INTO NVSEGMENT (SEGMENT_NO, USER_ID, GRP_CD, SEGMENT_NM, DBINFO_SEQ, SEGMENT_DESC, SQLHEAD, SQLTAIL, SQLBODY, SQLFILTER, LASTUPDATE_DT, SEGMENT_SIZE, CRTGRP_CD, SEGMENT_TYPE, FILETODB_YN, EDITOR_ID, SHARE_YN, ACTIVE_YN, CATEGORY_CD, SEGMENT_STS, TAG_NO, PSEGMENT_NO, PLINK_SEQ, SEG_TYPE, TESTQUERY, UPDATEQUERY)
VALUES(-1, 'admin', '01', 'DEFAULT TARGET', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 이케어 준실시간 옴니채널용 기준 시멘틱
INSERT INTO NVSEMANTIC (SEGMENT_NO, FIELD_SEQ, FIELD_NM, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, INITVALUE, MINVALUE, MAXVALUE, NULL_YN, FIELD_KEY)
VALUES(-1, 1, 'RECEIVER_ID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'K');
INSERT INTO NVSEMANTIC (SEGMENT_NO, FIELD_SEQ, FIELD_NM, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, INITVALUE, MINVALUE, MAXVALUE, NULL_YN, FIELD_KEY)
VALUES(-1, 2, 'RECEIVER_NM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'N');
INSERT INTO NVSEMANTIC (SEGMENT_NO, FIELD_SEQ, FIELD_NM, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, INITVALUE, MINVALUE, MAXVALUE, NULL_YN, FIELD_KEY)
VALUES(-1, 3, 'RECEIVER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'E');

-- PUSH 공통 코드 분류
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP01', '-', '00', 'PUSH 공통 코드', 'PUSH에서 사용하는 공통 코드', 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS') , null, 'vn');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0101', '-', 'AP01', 'PUSH 메시지 유형', 'PUSH 메시지 유형', 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS') , null, 'vn');