-- 사용자메뉴권한 : 관리자
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '01', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0102', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0103', 'R', 'W', 'X');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0104', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '02', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0202', 'R', 'W', 'X');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0204', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0205', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '03', 'R', NULL, NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030101', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030105', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030106', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030108', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030109', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '030204', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '04', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0401', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0402', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0403', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0404', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0405', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0406', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0407', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0408', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '05', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0501', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0502', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0504', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '06', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0603', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0604', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0606', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0607', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0608', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0701', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0702', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0703', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0704', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0705', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0706', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0707', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0708', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0710', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0711', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0712', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0715', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '10', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1001', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1002', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '100201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '100202', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '100203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1003', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '100301', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '100302', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '100303', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1004', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1005', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1006', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '1007', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0713', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0714', 'R', 'W', NULL);

-- 사용자메뉴권한 : manager
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '01', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0102', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0103', 'R', 'W', 'X');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0104', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '02', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0202', 'R', 'W', 'X');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '03', 'R', NULL, NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030101', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030105', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030106', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030107', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030108', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030109', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '030203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '04', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0401', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0402', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0403', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0404', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '05', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0501', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0502', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0504', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '06', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0603', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0604', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0605', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0607', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0608', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0701', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0702', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0703', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0704', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0705', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0706', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0707', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0708', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0710', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0711', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0712', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0715', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '10', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1001', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1002', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '100201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '100202', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '100203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1003', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '100301', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '100302', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '100303', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1004', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1005', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1006', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '1007', 'R', 'W', NULL);

-- 사용자메뉴권한 : 테스터
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '01', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0102', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0103', 'R', 'W', 'X');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0104', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '02', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0202', 'R', 'W', 'X');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '03', 'R', NULL, NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030101', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030105', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030106', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030107', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030108', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030109', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '030203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '04', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0401', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0402', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0403', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0404', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '05', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0501', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0502', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0504', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '06', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0603', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0604', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0605', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0606', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0608', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0701', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0702', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0703', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0704', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0705', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0706', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0707', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0708', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0710', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0711', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0712', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0715', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '10', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1001', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1002', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '100201', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '100202', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '100203', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1003', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '100301', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '100302', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '100303', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1004', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1005', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1006', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '1007', 'R', 'W', NULL);


-- 브랜드톡 추가
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0407', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0407', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('manager', '0408', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('test', '0408', 'R', 'W', NULL);

--리포트 더미 테이블 데이터
INSERT INTO COPY_T (NO, CHR) VALUES (1, '1');
INSERT INTO COPY_T (NO, CHR) VALUES (2, '2');
INSERT INTO COPY_T (NO, CHR) VALUES (3, '3');
INSERT INTO COPY_T (NO, CHR) VALUES (4, '4');
INSERT INTO COPY_T (NO, CHR) VALUES (5, '5');
INSERT INTO COPY_T (NO, CHR) VALUES (6, '6');
INSERT INTO COPY_T (NO, CHR) VALUES (7, '7');
INSERT INTO COPY_T (NO, CHR) VALUES (8, '8');
INSERT INTO COPY_T (NO, CHR) VALUES (9, '9');
INSERT INTO COPY_T (NO, CHR) VALUES (10, '10');
INSERT INTO COPY_T (NO, CHR) VALUES (11, '11');
INSERT INTO COPY_T (NO, CHR) VALUES (12, '12');
INSERT INTO COPY_T (NO, CHR) VALUES (13, '13');
INSERT INTO COPY_T (NO, CHR) VALUES (14, '14');
INSERT INTO COPY_T (NO, CHR) VALUES (15, '15');
INSERT INTO COPY_T (NO, CHR) VALUES (16, '16');
INSERT INTO COPY_T (NO, CHR) VALUES (17, '17');
INSERT INTO COPY_T (NO, CHR) VALUES (18, '18');
INSERT INTO COPY_T (NO, CHR) VALUES (19, '19');
INSERT INTO COPY_T (NO, CHR) VALUES (20, '20');
INSERT INTO COPY_T (NO, CHR) VALUES (21, '21');
INSERT INTO COPY_T (NO, CHR) VALUES (22, '22');
INSERT INTO COPY_T (NO, CHR) VALUES (23, '23');
INSERT INTO COPY_T (NO, CHR) VALUES (24, '24');
INSERT INTO COPY_T (NO, CHR) VALUES (25, '25');
INSERT INTO COPY_T (NO, CHR) VALUES (26, '26');
INSERT INTO COPY_T (NO, CHR) VALUES (27, '27');
INSERT INTO COPY_T (NO, CHR) VALUES (28, '28');
INSERT INTO COPY_T (NO, CHR) VALUES (29, '29');
INSERT INTO COPY_T (NO, CHR) VALUES (30, '30');
INSERT INTO COPY_T (NO, CHR) VALUES (31, '31');
INSERT INTO COPY_T (NO, CHR) VALUES (32, '32');
INSERT INTO COPY_T (NO, CHR) VALUES (33, '33');
INSERT INTO COPY_T (NO, CHR) VALUES (34, '34');
INSERT INTO COPY_T (NO, CHR) VALUES (35, '35');
INSERT INTO COPY_T (NO, CHR) VALUES (36, '36');
INSERT INTO COPY_T (NO, CHR) VALUES (37, '37');
INSERT INTO COPY_T (NO, CHR) VALUES (38, '38');
INSERT INTO COPY_T (NO, CHR) VALUES (39, '39');
INSERT INTO COPY_T (NO, CHR) VALUES (40, '40');
INSERT INTO COPY_T (NO, CHR) VALUES (41, '41');
INSERT INTO COPY_T (NO, CHR) VALUES (42, '42');
INSERT INTO COPY_T (NO, CHR) VALUES (43, '43');
INSERT INTO COPY_T (NO, CHR) VALUES (44, '44');
INSERT INTO COPY_T (NO, CHR) VALUES (45, '45');
INSERT INTO COPY_T (NO, CHR) VALUES (46, '46');
INSERT INTO COPY_T (NO, CHR) VALUES (47, '47');
INSERT INTO COPY_T (NO, CHR) VALUES (48, '48');
INSERT INTO COPY_T (NO, CHR) VALUES (49, '49');
INSERT INTO COPY_T (NO, CHR) VALUES (50, '50');
INSERT INTO COPY_T (NO, CHR) VALUES (51, '51');
INSERT INTO COPY_T (NO, CHR) VALUES (52, '52');
INSERT INTO COPY_T (NO, CHR) VALUES (53, '53');
INSERT INTO COPY_T (NO, CHR) VALUES (54, '54');
INSERT INTO COPY_T (NO, CHR) VALUES (55, '55');
INSERT INTO COPY_T (NO, CHR) VALUES (56, '56');
INSERT INTO COPY_T (NO, CHR) VALUES (57, '57');
INSERT INTO COPY_T (NO, CHR) VALUES (58, '58');
INSERT INTO COPY_T (NO, CHR) VALUES (59, '59');
INSERT INTO COPY_T (NO, CHR) VALUES (60, '60');
INSERT INTO COPY_T (NO, CHR) VALUES (61, '61');
INSERT INTO COPY_T (NO, CHR) VALUES (62, '62');
INSERT INTO COPY_T (NO, CHR) VALUES (63, '63');
INSERT INTO COPY_T (NO, CHR) VALUES (64, '64');
INSERT INTO COPY_T (NO, CHR) VALUES (65, '65');
INSERT INTO COPY_T (NO, CHR) VALUES (66, '66');
INSERT INTO COPY_T (NO, CHR) VALUES (67, '67');
INSERT INTO COPY_T (NO, CHR) VALUES (68, '68');
INSERT INTO COPY_T (NO, CHR) VALUES (69, '69');
INSERT INTO COPY_T (NO, CHR) VALUES (70, '70');
INSERT INTO COPY_T (NO, CHR) VALUES (71, '71');
INSERT INTO COPY_T (NO, CHR) VALUES (72, '72');
INSERT INTO COPY_T (NO, CHR) VALUES (73, '73');
INSERT INTO COPY_T (NO, CHR) VALUES (74, '74');
INSERT INTO COPY_T (NO, CHR) VALUES (75, '75');
INSERT INTO COPY_T (NO, CHR) VALUES (76, '76');
INSERT INTO COPY_T (NO, CHR) VALUES (77, '77');
INSERT INTO COPY_T (NO, CHR) VALUES (78, '78');
INSERT INTO COPY_T (NO, CHR) VALUES (79, '79');
INSERT INTO COPY_T (NO, CHR) VALUES (80, '80');
INSERT INTO COPY_T (NO, CHR) VALUES (81, '81');
INSERT INTO COPY_T (NO, CHR) VALUES (82, '82');
INSERT INTO COPY_T (NO, CHR) VALUES (83, '83');
INSERT INTO COPY_T (NO, CHR) VALUES (84, '84');
INSERT INTO COPY_T (NO, CHR) VALUES (85, '85');
INSERT INTO COPY_T (NO, CHR) VALUES (86, '86');
INSERT INTO COPY_T (NO, CHR) VALUES (87, '87');
INSERT INTO COPY_T (NO, CHR) VALUES (88, '88');
INSERT INTO COPY_T (NO, CHR) VALUES (89, '89');
INSERT INTO COPY_T (NO, CHR) VALUES (90, '90');
INSERT INTO COPY_T (NO, CHR) VALUES (91, '91');
INSERT INTO COPY_T (NO, CHR) VALUES (92, '92');
INSERT INTO COPY_T (NO, CHR) VALUES (93, '93');
INSERT INTO COPY_T (NO, CHR) VALUES (94, '94');
INSERT INTO COPY_T (NO, CHR) VALUES (95, '95');
INSERT INTO COPY_T (NO, CHR) VALUES (96, '96');
INSERT INTO COPY_T (NO, CHR) VALUES (97, '97');
INSERT INTO COPY_T (NO, CHR) VALUES (98, '98');
INSERT INTO COPY_T (NO, CHR) VALUES (99, '99');
INSERT INTO COPY_T (NO, CHR) VALUES (100, '100');