/****************************************************************
 * ALTER
 * DB암호화로 인한 사이즈 변경
 * SMS: 25 ->88  (->100)
 * 이메일:100 ->152 (->256)
 * 이름: 100 ->152 (->256)
*****************************************************************/

ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_TEL           SET DATA TYPE VARCHAR(100);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_FAX           SET DATA TYPE VARCHAR(256);

ALTER TABLE NVSENDLOG 	          ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVSENDLOG	          ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);
ALTER TABLE NVTESTSENDLOG         ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVTESTSENDLOG         ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECAREMSG            ALTER COLUMN RECEIVER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECAREMSG            ALTER COLUMN SENDER_TEL             SET DATA TYPE VARCHAR(100);
ALTER TABLE NVECAREMSG            ALTER COLUMN SENDER_EMAIL           SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECAREMSG            ALTER COLUMN SENDER_NM              SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECAREMSG            ALTER COLUMN RETMAIL_RECEIVER       SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECAREMIMEINFOLOG    ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECAREMIMEINFOLOG    ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECARESENDLOG        ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECARESENDLOG        ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVTESTECARESENDLOG    ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVTESTECARESENDLOG    ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVDBINFO              ALTER COLUMN DBPASSWORD             SET DATA TYPE VARCHAR(100);

ALTER TABLE NVTESTUSERPOOL        ALTER COLUMN TESTRECEIVER_EMAIL     SET DATA TYPE VARCHAR(256);
ALTER TABLE NVTESTUSERPOOL        ALTER COLUMN TESTRECEIVER_NM        SET DATA TYPE VARCHAR(256);
ALTER TABLE NVTESTUSERPOOL        ALTER COLUMN TESTRECEIVER_TEL       SET DATA TYPE VARCHAR(100);
ALTER TABLE NVTESTUSERPOOL        ALTER COLUMN TESTRECEIVER_FAX       SET DATA TYPE VARCHAR(100);

ALTER TABLE NVUSERMAILINFO        ALTER COLUMN SENDER_NM              SET DATA TYPE VARCHAR(256);
ALTER TABLE NVUSERMAILINFO        ALTER COLUMN SENDER_EMAIL           SET DATA TYPE VARCHAR(256);
ALTER TABLE NVUSERMAILINFO        ALTER COLUMN RECEIVER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVUSERMAILINFO        ALTER COLUMN SENDER_TEL             SET DATA TYPE VARCHAR(100);
ALTER TABLE NVUSERMAILINFO        ALTER COLUMN SENDER_FAX             SET DATA TYPE VARCHAR(100);
ALTER TABLE NVUSERMAILINFO        ALTER COLUMN RECEIVER_FAX           SET DATA TYPE VARCHAR(100);
ALTER TABLE NVUSERMAILINFO        ALTER COLUMN RETMAIL_RECEIVER       SET DATA TYPE VARCHAR(256);

ALTER TABLE NVREALTIMEACCEPT      ALTER COLUMN RECEIVER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVREALTIMEACCEPT      ALTER COLUMN RECEIVER               SET DATA TYPE VARCHAR(256);
ALTER TABLE NVREALTIMEACCEPT      ALTER COLUMN SENDER_NM              SET DATA TYPE VARCHAR(256);
ALTER TABLE NVREALTIMEACCEPT      ALTER COLUMN SENDER                 SET DATA TYPE VARCHAR(256);

ALTER TABLE NVSCHEDULEACCEPT      ALTER COLUMN RECEIVER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVSCHEDULEACCEPT      ALTER COLUMN RECEIVER               SET DATA TYPE VARCHAR(256);
ALTER TABLE NVSCHEDULEACCEPT      ALTER COLUMN SENDER_NM              SET DATA TYPE VARCHAR(256);
ALTER TABLE NVSCHEDULEACCEPT      ALTER COLUMN SENDER                 SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECARELINKRESULT     ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECARELINKRESULT     ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECAREREJECT         ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECAREREJECT         ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECARERETURNMAIL     ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVECARERETURNMAIL     ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVLINKRESULT          ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVLINKRESULT          ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVREJECT              ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVREJECT              ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);

ALTER TABLE NVRETURNMAIL          ALTER COLUMN CUSTOMER_NM            SET DATA TYPE VARCHAR(256);
ALTER TABLE NVRETURNMAIL          ALTER COLUMN CUSTOMER_EMAIL         SET DATA TYPE VARCHAR(256);


ALTER TABLE NVFILEUPLOAD          ALTER COLUMN  CALL_BACK    	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVECARERECEIPT        ALTER COLUMN CUSTOMER_EMAIL     	SET DATA TYPE VARCHAR(256);
ALTER TABLE NVMIMEINFOLOG         ALTER COLUMN CUSTOMER_EMAIL     	SET DATA TYPE VARCHAR(256);
ALTER TABLE NVRECEIPT             ALTER COLUMN CUSTOMER_EMAIL     	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECARERECEIPT        ALTER COLUMN CUSTOMER_NM        	SET DATA TYPE VARCHAR(256);
ALTER TABLE NVMIMEINFOLOG         ALTER COLUMN CUSTOMER_NM        	SET DATA TYPE VARCHAR(256);
ALTER TABLE NVRECEIPT             ALTER COLUMN CUSTOMER_NM        	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_SLOT1        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_SLOT2        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN CUSTOMER_TEL        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVSERVERINFO          ALTER COLUMN DBPASSWORD         	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVUSER              	ALTER COLUMN EMAIL         	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVECAREKMMAP          ALTER COLUMN ITEM_PRAM_VALUE         	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVUSERGRP             ALTER COLUMN MANAGER_NM         	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVECARESENDLOG  			ALTER COLUMN MESSAGE_KEY         	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVSENDLOG        	    ALTER COLUMN MESSAGE_KEY         	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVTESTECARESENDLOG   	ALTER COLUMN MESSAGE_KEY         	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVTESTSENDLOG	        ALTER COLUMN MESSAGE_KEY         	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVUSER 	         	    ALTER COLUMN NAME_ENG         	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVUSER 	         	    ALTER COLUMN NAME_KOR         	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVUSER 	         	    ALTER COLUMN PASS_WD         	SET DATA TYPE VARCHAR(256);
ALTER TABLE NVUSERPWHISTORY 			ALTER COLUMN PASS_WD         	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVCAMPAIGN            ALTER COLUMN RECEIVER_NM        	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVREALTIMEACCEPT     	ALTER COLUMN SECU_KEY        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVREALTIMEACCEPTDATA  ALTER COLUMN SECU_KEY        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVSCHEDULEACCEPT    	ALTER COLUMN SECU_KEY        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVSCHEDULEACCEPTDATA  ALTER COLUMN SECU_KEY        	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVCAMPAIGN            ALTER COLUMN SENDER_EMAIL        	SET DATA TYPE VARCHAR(256);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN SENDER_EMAIL        	SET DATA TYPE VARCHAR(256);

ALTER TABLE NVCAMPAIGN            ALTER COLUMN SENDER_NM        	SET DATA TYPE VARCHAR(100);
ALTER TABLE NVFILEUPLOAD          ALTER COLUMN SENDER_NM        	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVCAMPAIGN            ALTER COLUMN SENDER_TEL         	SET DATA TYPE VARCHAR(100);

ALTER TABLE NVUSER                ALTER COLUMN TEL_NO         	SET DATA TYPE VARCHAR(100);

/****************************************************************
 * 기본 사용자 정보 변경 (default: Aria 사용시)
*****************************************************************/
UPDATE NVUSER
SET NAME_KOR='3EE9C92DB3C4ADA25DF79FFCBABB3107', NAME_ENG='39DD2707A7EA1A04D149DE1948A203AD', TEL_NO='9E6E05A271870D9324E4FE8D2BBDA754', EMAIL='A9551A6D2796C6D19188E66427F03B09'
WHERE USER_ID='admin';

UPDATE NVUSER
SET NAME_KOR='1226361BB6F228B307F9590BC2CA61BA', NAME_ENG='F2447C4E584FF7CF9DCA7504E3086B4C', TEL_NO='9E6E05A271870D9324E4FE8D2BBDA754', EMAIL='7E1BFAA7138628F59DCCFE56A543CE450DD3977473AA8356CE4ACBDAAF2B1FE5'
WHERE USER_ID='manager';

UPDATE NVUSER
SET NAME_KOR='71C788D06567E2DA07A89AE1E93EAFA2', NAME_ENG='D17C7DF6824BC4E6D90234ABE3948F29', TEL_NO='9E6E05A271870D9324E4FE8D2BBDA754', EMAIL='5235C0A703F7295CF0751A8AAA333C1E'
WHERE USER_ID='test';