-- 02_wiseU5_create_table_campaign.sql 파일 테이블 drop
DROP TABLE NVSCENARIO;
DROP TABLE NVCAMPAIGN;
DROP TABLE NVCAMPTAG;
DROP TABLE NVSCHEDULE;
DROP TABLE NVAPPLICATION;
DROP TABLE NVTEMPLATE;
DROP TABLE NVMULTIPARTFILE;
DROP TABLE NVTRACEINFO;
DROP TABLE NVLINKCONDITION;
DROP TABLE NVLINKTRACE;
DROP TABLE NVMIMEINFOLOG;
DROP TABLE NVSENDRESULT;
DROP TABLE NVSENDLOG;
DROP TABLE NVTESTSENDLOG;
DROP TABLE NVSENDRESULTDETAIL;
DROP TABLE NV_SPAM_SENDLOG;

-- 05_wiseU5_create_table_receive.sql 파일 테이블 drop
DROP TABLE NVECARELINKRESULT;
DROP TABLE NVECARERECEIPT;
DROP TABLE NVECAREREJECT;
DROP TABLE NVECARERETURNMAIL;
DROP TABLE NVLINKRESULT;
DROP TABLE NVRECEIPT;
DROP TABLE NVREJECT;
DROP TABLE NVRETURNMAIL;
