-- 캠페인
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '01';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0102';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0103';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0104';

-- 컨텐츠 변경이력
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0204';

-- 리포트
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0301';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '030101';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '030105';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '030106';

-- 템플릿
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0401';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0402';

UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0502';

UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0603';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0604';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0605';

UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0701';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0703';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0704';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0705';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0707';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0710';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0714';
UPDATE NVMENU SET ACTIVE_YN = 'N' WHERE MENU_CD = '0715';

-- 메뉴 활성화
UPDATE NVMENU SET ACTIVE_YN = 'Y' WHERE MENU_CD = '0205';
UPDATE NVMENU SET ACTIVE_YN = 'Y' WHERE MENU_CD = '0403';
UPDATE NVMENU SET ACTIVE_YN = 'Y' WHERE MENU_CD = '0404';

-- 리포트 메뉴의 기본 URL을 이케어 리스트도 변경
UPDATE NVMENU SET MENU_LINK_URL = '/report/ecare/ecareRptList.do' WHERE MENU_CD = '03';
UPDATE NVMENU SET MENU_LINK_URL = '/template/mobileTemplateList.do' WHERE MENU_CD = '04';

-- 이케어 메뉴명을 메시지로 변경
UPDATE NVMENU_LANG SET MENU_NM = '메시지' WHERE MENU_CD = '02' AND LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '메시지 리스트' WHERE MENU_CD = '0201' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '메시지 등록' WHERE MENU_CD = '0202' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '메시지 고객이력' WHERE MENU_CD = '0203' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '메시지' WHERE MENU_CD = '0302' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '메시지 리스트' WHERE MENU_CD = '030201' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '메시지이력관리' WHERE MENU_CD = '0713' AND   LANG = 'ko';