CREATE TABLE NV_API_LOG (
	REGDATE					VARCHAR2(17)        NOT NULL,
	SEQ                     VARCHAR2(100)       NOT NULL,
	REGTYPE					VARCHAR2(1)         DEFAULT 'L' NOT NULL,
	INTERFACE_ID			VARCHAR2(100),
	MSG						VARCHAR2(4000),
	IN_VAL					CLOB,
	DTL_MSG					CLOB
);
ALTER TABLE NV_API_LOG ADD CONSTRAINT PK_NV_LOG_API PRIMARY KEY (REGDATE,SEQ);

COMMENT ON TABLE  NV_API_LOG IS 'API 로그관리';
COMMENT ON COLUMN NV_API_LOG.REGDATE 		IS '등록 일시 YYYYMMDDHH24MISS.SSS';
COMMENT ON COLUMN NV_API_LOG.SEQ			IS '등록 난수';
COMMENT ON COLUMN NV_API_LOG.REGTYPE 		IS '로그 타입 L : 일반로그, E : 에러';
COMMENT ON COLUMN NV_API_LOG.INTERFACE_ID 	IS '인터페이스 ID';
COMMENT ON COLUMN NV_API_LOG.MSG 			IS '메세지';
COMMENT ON COLUMN NV_API_LOG.IN_VAL 		IS '입력전문';
COMMENT ON COLUMN NV_API_LOG.DTL_MSG 		IS '상세 메세지';
-- 캠페인 사용 여부추가
ALTER TABLE NVCAMPAIGN ADD USE_YN CHAR(1) DEFAULT 'Y';
-- 이케어 사용 여부추가
ALTER TABLE NVECAREMSG ADD USE_YN CHAR(1) DEFAULT 'Y';