-- SMS 리포트 전송 성공자 다운로드
CREATE VIEW V_SMS_SUCCESS_FILE_LOG (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE
) AS
SELECT
    TR_ID AS TRAN_ID, TR_PHONE AS TRAN_PHONE, TRAN_DATE, TR_RSLTSTAT AS TRAN_RSLT, SERVICE_TYPE,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TR_ETC2 AS TRAN_TYPE
FROM SC_LOG
WHERE TR_RSLTSTAT = '06'
UNION ALL
SELECT
    ID AS TRAN_ID, PHONE AS TRAN_PHONE, TRAN_DATE, RSLT AS TRAN_RSLT, SERVICE_TYPE,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, ETC2 AS TRAN_TYPE
FROM MMS_LOG
WHERE RSLT = '1000';

-- SMS 리포트 전송 실패자 다운로드
CREATE VIEW V_SMS_FAIL_FILE_LOG (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE
) AS
SELECT
    TR_ID AS TRAN_ID, TR_PHONE AS TRAN_PHONE, TO_CHAR(TR_SENDDATE, 'YYYY-MM-DD HH24:MI') TRAN_DATE, TR_RSLTSTAT AS TRAN_RSLT, SERVICE_TYPE,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TR_ETC2 AS TRAN_TYPE
FROM SC_LOG
WHERE TR_RSLTSTAT = '06'
UNION ALL
SELECT
    ID AS TRAN_ID, PHONE AS TRAN_PHONE, TO_CHAR(REQDATE, 'YYYY-MM-DD HH24:MI') TRAN_DATE, RSLT AS TRAN_RSLT, SERVICE_TYPE,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, ETC2 AS TRAN_TYPE
FROM MMS_LOG
WHERE RSLT = '1000';

-- SMS 리포트 오류 분석 리스트
CREATE VIEW V_SMS_ERROR_RESULT (
    TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ
) AS
SELECT
    TO_CHAR(TR_SENDDATE,'YYYYMMDD') AS TRAN_DATE, TR_RSLTSTAT AS TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ
FROM SC_LOG
WHERE TR_RSLTSTAT NOT IN ('06')
UNION ALL
SELECT
    TO_CHAR(REQDATE,'YYYYMMDD') AS TRAN_DATE, RSLT AS TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ
FROM MMS_LOG
WHERE RSLT NOT IN ('1000');

-- 연동 쪽에서 SMS 결과를 조회하는 용도 (NVREALTIMEACCEPT를 통한 준실시간 연동에서 사용)
CREATE VIEW VIEW_SMS_LOG (
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, STATUS,
    TRAN_RSLT, TRAN_MSG, SMS_TYPE, SLOT1, SLOT2, SEQ
) AS
SELECT
    PHONE, CALLBACK, RSLTDATE AS TRAN_RSLTDATE, REQ_USER_ID, STATUS,
    (CASE WHEN STATUS='3' AND RSLT='1000' THEN '06' ELSE RSLT END) AS RSLT, MSG, ETC2, SLOT1, SLOT2, SEQ
FROM MMS_LOG
UNION ALL
SELECT
    TR_PHONE, TR_CALLBACK, TR_RSLTDATE, REQ_USER_ID, '3',
    TR_RSLTSTAT, TR_MSG, 'SMS', SLOT1, SLOT2, SEQ
FROM SC_LOG;
