-- wiseU 7.2.7 -> 7.3.0 업그레이드 시 사용
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0407', '04', 1, '브랜드톡 리스트', '/template/brandtalkTemplateList.do', NULL, 'Y', 'template', 7, 'M');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES ('0407', 'ko', '브랜드톡 리스트');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0407', 'R', 'W', NULL);

INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0408', '04', 1, '브랜드톡 등록', '/template/brandtalkTemplateReg.do', NULL, 'Y', 'template', 8, 'M');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES ('0408', 'ko', '브랜드톡 등록');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0408', 'R', 'W', NULL);


--테이블 추가
ALTER TABLE NVMOBILECONTENTS ADD CONTENT_TYPE VARCHAR(10) ;
ALTER TABLE NVMOBILECONTENTS ADD UNSUBSCRIBE_CONTENT VARCHAR(20);
ALTER TABLE NVMOBILECONTENTS ADD MESSAGE_TYPE   VARCHAR(10);
SELECT * FROM NVMOBILECONTENTS;

ALTER TABLE NVMOBILECONTENTS ALTER COLUMN KAKAO_TMPL_CD SET DATA TYPE VARCHAR(50);
ALTER TABLE NVMOBILECONTENTS ALTER COLUMN CONTS_NM SET DATA TYPE VARCHAR(200);

--카카오 탬플릿 코드 변경(브랜드톡이 50자리)
ALTER TABLE NVCAMPAIGN ALTER COLUMN KAKAO_TMPL_CD SET DATA TYPE VARCHAR(50);
ALTER TABLE NVECAREMSG ALTER COLUMN KAKAO_TMPL_CD SET DATA TYPE VARCHAR(50);
ALTER TABLE NVKAKAORPTSENDRESULT ALTER COLUMN TMPL_CD SET DATA TYPE  VARCHAR(50);


--브랜드톡 에러코드가 5자리
ALTER TABLE NVSENDLOG ALTER COLUMN ERROR_CD SET DATA TYPE VARCHAR(5);
ALTER TABLE NVECARESENDLOG ALTER COLUMN ERROR_CD SET DATA TYPE VARCHAR(5);
-- 문자/카카오톡 메세지 일부 저장
ALTER TABLE NVSENDLOG ADD PART_MESSAGE VARCHAR(500);
ALTER TABLE NVECARESENDLOG ADD PART_MESSAGE VARCHAR(500);
ALTER TABLE NVTESTSENDLOG ADD PART_MESSAGE VARCHAR(500);
ALTER TABLE NVTESTECARESENDLOG ADD PART_MESSAGE VARCHAR(500);
-- 대체발송여부/대체발송 결과코드
ALTER TABLE NVSENDLOG ADD FAIL_BACK_CHANNEL VARCHAR(1);
ALTER TABLE NVECARESENDLOG ADD FAIL_BACK_CHANNEL VARCHAR(1);
ALTER TABLE NVSENDLOG ADD FAIL_BACK_RESULT_CD VARCHAR(5);
ALTER TABLE NVECARESENDLOG ADD FAIL_BACK_RESULT_CD VARCHAR(5);
--대체발송 발송시간
ALTER TABLE NVSENDLOG ADD FAIL_BACK_SENDDTM VARCHAR(14);
ALTER TABLE NVECARESENDLOG ADD FAIL_BACK_SENDDTM VARCHAR(14);

--템플릿 코드 적재
ALTER TABLE NVSENDLOG ADD TMPL_CD VARCHAR(50);
ALTER TABLE NVECARESENDLOG ADD TMPL_CD VARCHAR(50);
ALTER TABLE NVTESTSENDLOG ADD TMPL_CD VARCHAR(50);
ALTER TABLE NVTESTECARESENDLOG ADD TMPL_CD VARCHAR(50);

-- 결과 코드추가
INSERT INTO NVSENDERR (ERROR_CD, ERROR_NM, ERROR_DESC, ERROR_SMS_DESC, CATEGORY_CD, CHANNEL_TYPE, SPAM_YN)
VALUES('900', NULL, '핸들러 오류', NULL, '0106', 'M', 'N');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AF0001', '900', 'AF00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AS0001', '900', 'AS00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AB0001', '900', 'AB00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AC0001', '900', 'AC00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AA0001', '900', 'AA00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AS0001', 'v', 'AS00', '발신자 번호 미등록', '발신자 번호 미등록', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
-- 미사용 메뉴 삭제(접속로그,사용자로그,세션로그)
DELETE FROM NVMENU WHERE MENU_CD in('0603','0604','0605');
DELETE FROM NVMENU_LANG WHERE MENU_CD in('0603','0604','0605');
DELETE FROM NVMENUROLE WHERE MENU_CD in('0603','0604','0605');