-- 쿼리 수정
-- 리포트 메뉴 dept 삭제, 월별 발송 통계 중복 명칭 변경
update nvmenu set PMENU_CD='03',LEVEL_NO=1 where MENU_CD in('030106','030107','030203','030204','030201','030101','030105');
delete from nvmenu where MENU_CD in('0301','0302');
update nvmenu  set MENU_NM='캠페인 월별 통계' where MENU_CD='030106';
update nvmenu  set MENU_NM='이케어 월별 통계' where MENU_CD='030203';
update nvmenu_lang set MENU_NM='캠페인 월별 통계' where MENU_CD='030106' and lang='ko';
update nvmenu_lang set MENU_NM='이케어 월별 통계' where MENU_CD='030203' and lang='ko';
update nvmenu_lang set MENU_NM='Campaign monthly report' where MENU_CD='030106' and lang='en';
update nvmenu_lang set MENU_NM='Ecare monthly report' where MENU_CD='030203' and lang='en';
update nvserverinfo set ALTALK_RESEND_ERROR_CD = '0000,A1000' where HOST_NM = '1';
-- 리포트 더미 테이블 생성
CREATE TABLE COPY_T (
    NO                        NUMERIC(3)              NOT NULL,
    CHR                       VARCHAR(3)          NOT NULL
);

INSERT INTO COPY_T (NO, CHR) VALUES (1, '1');
INSERT INTO COPY_T (NO, CHR) VALUES (2, '2');
INSERT INTO COPY_T (NO, CHR) VALUES (3, '3');
INSERT INTO COPY_T (NO, CHR) VALUES (4, '4');
INSERT INTO COPY_T (NO, CHR) VALUES (5, '5');
INSERT INTO COPY_T (NO, CHR) VALUES (6, '6');
INSERT INTO COPY_T (NO, CHR) VALUES (7, '7');
INSERT INTO COPY_T (NO, CHR) VALUES (8, '8');
INSERT INTO COPY_T (NO, CHR) VALUES (9, '9');
INSERT INTO COPY_T (NO, CHR) VALUES (10, '10');
INSERT INTO COPY_T (NO, CHR) VALUES (11, '11');
INSERT INTO COPY_T (NO, CHR) VALUES (12, '12');
INSERT INTO COPY_T (NO, CHR) VALUES (13, '13');
INSERT INTO COPY_T (NO, CHR) VALUES (14, '14');
INSERT INTO COPY_T (NO, CHR) VALUES (15, '15');
INSERT INTO COPY_T (NO, CHR) VALUES (16, '16');
INSERT INTO COPY_T (NO, CHR) VALUES (17, '17');
INSERT INTO COPY_T (NO, CHR) VALUES (18, '18');
INSERT INTO COPY_T (NO, CHR) VALUES (19, '19');
INSERT INTO COPY_T (NO, CHR) VALUES (20, '20');
INSERT INTO COPY_T (NO, CHR) VALUES (21, '21');
INSERT INTO COPY_T (NO, CHR) VALUES (22, '22');
INSERT INTO COPY_T (NO, CHR) VALUES (23, '23');
INSERT INTO COPY_T (NO, CHR) VALUES (24, '24');
INSERT INTO COPY_T (NO, CHR) VALUES (25, '25');
INSERT INTO COPY_T (NO, CHR) VALUES (26, '26');
INSERT INTO COPY_T (NO, CHR) VALUES (27, '27');
INSERT INTO COPY_T (NO, CHR) VALUES (28, '28');
INSERT INTO COPY_T (NO, CHR) VALUES (29, '29');
INSERT INTO COPY_T (NO, CHR) VALUES (30, '30');
INSERT INTO COPY_T (NO, CHR) VALUES (31, '31');
INSERT INTO COPY_T (NO, CHR) VALUES (32, '32');
INSERT INTO COPY_T (NO, CHR) VALUES (33, '33');
INSERT INTO COPY_T (NO, CHR) VALUES (34, '34');
INSERT INTO COPY_T (NO, CHR) VALUES (35, '35');
INSERT INTO COPY_T (NO, CHR) VALUES (36, '36');
INSERT INTO COPY_T (NO, CHR) VALUES (37, '37');
INSERT INTO COPY_T (NO, CHR) VALUES (38, '38');
INSERT INTO COPY_T (NO, CHR) VALUES (39, '39');
INSERT INTO COPY_T (NO, CHR) VALUES (40, '40');
INSERT INTO COPY_T (NO, CHR) VALUES (41, '41');
INSERT INTO COPY_T (NO, CHR) VALUES (42, '42');
INSERT INTO COPY_T (NO, CHR) VALUES (43, '43');
INSERT INTO COPY_T (NO, CHR) VALUES (44, '44');
INSERT INTO COPY_T (NO, CHR) VALUES (45, '45');
INSERT INTO COPY_T (NO, CHR) VALUES (46, '46');
INSERT INTO COPY_T (NO, CHR) VALUES (47, '47');
INSERT INTO COPY_T (NO, CHR) VALUES (48, '48');
INSERT INTO COPY_T (NO, CHR) VALUES (49, '49');
INSERT INTO COPY_T (NO, CHR) VALUES (50, '50');
INSERT INTO COPY_T (NO, CHR) VALUES (51, '51');
INSERT INTO COPY_T (NO, CHR) VALUES (52, '52');
INSERT INTO COPY_T (NO, CHR) VALUES (53, '53');
INSERT INTO COPY_T (NO, CHR) VALUES (54, '54');
INSERT INTO COPY_T (NO, CHR) VALUES (55, '55');
INSERT INTO COPY_T (NO, CHR) VALUES (56, '56');
INSERT INTO COPY_T (NO, CHR) VALUES (57, '57');
INSERT INTO COPY_T (NO, CHR) VALUES (58, '58');
INSERT INTO COPY_T (NO, CHR) VALUES (59, '59');
INSERT INTO COPY_T (NO, CHR) VALUES (60, '60');
INSERT INTO COPY_T (NO, CHR) VALUES (61, '61');
INSERT INTO COPY_T (NO, CHR) VALUES (62, '62');
INSERT INTO COPY_T (NO, CHR) VALUES (63, '63');
INSERT INTO COPY_T (NO, CHR) VALUES (64, '64');
INSERT INTO COPY_T (NO, CHR) VALUES (65, '65');
INSERT INTO COPY_T (NO, CHR) VALUES (66, '66');
INSERT INTO COPY_T (NO, CHR) VALUES (67, '67');
INSERT INTO COPY_T (NO, CHR) VALUES (68, '68');
INSERT INTO COPY_T (NO, CHR) VALUES (69, '69');
INSERT INTO COPY_T (NO, CHR) VALUES (70, '70');
INSERT INTO COPY_T (NO, CHR) VALUES (71, '71');
INSERT INTO COPY_T (NO, CHR) VALUES (72, '72');
INSERT INTO COPY_T (NO, CHR) VALUES (73, '73');
INSERT INTO COPY_T (NO, CHR) VALUES (74, '74');
INSERT INTO COPY_T (NO, CHR) VALUES (75, '75');
INSERT INTO COPY_T (NO, CHR) VALUES (76, '76');
INSERT INTO COPY_T (NO, CHR) VALUES (77, '77');
INSERT INTO COPY_T (NO, CHR) VALUES (78, '78');
INSERT INTO COPY_T (NO, CHR) VALUES (79, '79');
INSERT INTO COPY_T (NO, CHR) VALUES (80, '80');
INSERT INTO COPY_T (NO, CHR) VALUES (81, '81');
INSERT INTO COPY_T (NO, CHR) VALUES (82, '82');
INSERT INTO COPY_T (NO, CHR) VALUES (83, '83');
INSERT INTO COPY_T (NO, CHR) VALUES (84, '84');
INSERT INTO COPY_T (NO, CHR) VALUES (85, '85');
INSERT INTO COPY_T (NO, CHR) VALUES (86, '86');
INSERT INTO COPY_T (NO, CHR) VALUES (87, '87');
INSERT INTO COPY_T (NO, CHR) VALUES (88, '88');
INSERT INTO COPY_T (NO, CHR) VALUES (89, '89');
INSERT INTO COPY_T (NO, CHR) VALUES (90, '90');
INSERT INTO COPY_T (NO, CHR) VALUES (91, '91');
INSERT INTO COPY_T (NO, CHR) VALUES (92, '92');
INSERT INTO COPY_T (NO, CHR) VALUES (93, '93');
INSERT INTO COPY_T (NO, CHR) VALUES (94, '94');
INSERT INTO COPY_T (NO, CHR) VALUES (95, '95');
INSERT INTO COPY_T (NO, CHR) VALUES (96, '96');
INSERT INTO COPY_T (NO, CHR) VALUES (97, '97');
INSERT INTO COPY_T (NO, CHR) VALUES (98, '98');
INSERT INTO COPY_T (NO, CHR) VALUES (99, '99');
INSERT INTO COPY_T (NO, CHR) VALUES (100, '100');

-- 채널별 발송 중 코드 추가
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AA0001', '010', 'AA00', '발송중(결과수신전)', '발송중(결과수신전)', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AF0001', '010', 'AF00', '발송중(결과수신전)', '발송중(결과수신전)', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AC0001', '010', 'AC00', '발송중(결과수신전)', '발송중(결과수신전)', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AS0001', '010', 'AS00', '발송중(결과수신전)', '발송중(결과수신전)', NULL, 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0101', '010', 'AP0001', '발송중(결과수신전)', '발송중(결과수신전)', 'y', TO_CHAR(CURRENT TIMESTAMP, 'YYYYMMDDHH24MISS'), NULL, 'ko');