INSERT INTO nvdefaulthandler ( seq, handle_nm, handle_desc, service_type, channel, handle_type, handle_attr, user_id, create_dt, create_tm, handler, ab_test_yn)
VALUES (1, 'ecare', 'ecare', 'S', 'S', 'G', 'D', 'admin', '', '', ' ', 'N');
INSERT INTO nvdefaulthandler ( seq, handle_nm, handle_desc, service_type, channel, handle_type, handle_attr, user_id, create_dt, create_tm, handler, ab_test_yn)
VALUES (2, 'ecare', 'ecare', 'S', 'T', 'G', 'D', 'admin', '', '', ' ', 'N');
INSERT INTO nvdefaulthandler ( seq, handle_nm, handle_desc, service_type, channel, handle_type, handle_attr, user_id, create_dt, create_tm, handler, ab_test_yn)
VALUES (3, 'ecare', 'ecare', 'S', 'A', 'G', 'D', 'admin', '', '', ' ', 'N');
INSERT INTO nvdefaulthandler ( seq, handle_nm, handle_desc, service_type, channel, handle_type, handle_attr, user_id, create_dt, create_tm, handler, ab_test_yn)
VALUES (4, 'ecare', 'ecare', 'S', 'C', 'G', 'D', 'admin', '', '', ' ', 'N');

INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (1, 'admin', '01', 'SMS 기간계', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (2, 'admin', '01', 'LMS/MMS 기간계', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (3, 'admin', '01', '알림톡 기간계', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (4, 'admin', '01', '친구톡 기간계', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (5, 'admin', '01', 'SMS 단건 발송', NULL, NULL, '20180419', '20180417', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (6, 'admin', '01', 'LMS/MMS 단건 발송', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (7, 'admin', '01', '알림톡 단건발송', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);
INSERT INTO nvecarescenario
(scenario_no, user_id, grp_cd, scenario_nm, scenario_desc, scenario_type, create_dt, lastupdate_dt, finish_yn, finish_dt, create_tm, lastupdate_tm, service_type, tag_no, sub_type, handler_type, chrg_nm, brc_nm)
VALUES (8, 'admin', '01', '친구톡 단건발송', NULL, NULL, '20180419', '20180419', 'N', NULL, '000000', '000000', 'S', 1, 'S', 'G', NULL, NULL);

INSERT INTO NVSEGMENT
(SEGMENT_NO, USER_ID, GRP_CD, SEGMENT_NM, DBINFO_SEQ, SEGMENT_DESC, SQLHEAD, SQLTAIL, SQLBODY, SQLFILTER, LASTUPDATE_DT, SEGMENT_SIZE, CRTGRP_CD, SEGMENT_TYPE, FILETODB_YN, EDITOR_ID, SHARE_YN, ACTIVE_YN, CATEGORY_CD, SEGMENT_STS, TAG_NO, PSEGMENT_NO, PLINK_SEQ, SEG_TYPE, TESTQUERY, UPDATEQUERY)
VALUES (1, 'admin', '01', 'Default', 1, NULL, 'SELECT A.CUSTOMER_ID,A.CUSTOMER_NM,A.CUSTOMER_TEL FROM NVFILEUPLOAD A ', NULL, '  WHERE TARGET_NO = 1', NULL, '20180419', 1, NULL, 'N', 'Y', NULL, 'Y', 'Y', NULL, NULL, 1, 0, NULL, 'F', NULL, NULL);

INSERT INTO nvsemantic
(segment_no, field_seq, field_nm, field_desc, field_type, field_length, initvalue, `minvalue`, `maxvalue`, null_yn, field_key)
VALUES (1, 1, 'CUSTOMER_ID', '아이디', NULL, NULL, NULL, NULL, NULL, 'N', 'K');
INSERT INTO nvsemantic
(segment_no, field_seq, field_nm, field_desc, field_type, field_length, initvalue, `minvalue`, `maxvalue`, null_yn, field_key)
VALUES (1, 2, 'CUSTOMER_NM', '이름', NULL, NULL, NULL, NULL, NULL, 'N', 'N');
INSERT INTO nvsemantic
(segment_no, field_seq, field_nm, field_desc, field_type, field_length, initvalue, `minvalue`, `maxvalue`, null_yn, field_key)
VALUES (1, 3, 'CUSTOMER_TEL', '고객휴대폰', NULL, NULL, NULL, NULL, NULL, 'N', 'S');

INSERT INTO nvfileupload (target_no, customer_id, customer_nm, customer_email, customer_tel, customer_fax, slot1, slot2, slot3, slot4, slot5, slot6, slot7, slot8, slot9, slot10, slot11, slot12, slot13, slot14, slot15, slot16, slot17, slot18, slot19, slot20, slot21, slot22, slot23, slot24, slot25, slot26, slot27, slot28, slot29, slot30, slot31, slot32, slot33, slot34, slot35, slot36, slot37, slot38, slot39, slot40, slot41, slot42, slot43, slot44, slot45, slot46, slot47, slot48, slot49, slot50, seg, call_back, customer_slot1, customer_slot2, sender_nm, sender_email, retmail_receiver, sentence)
VALUES (1, '1', 'bizmsg', NULL, '01000000000', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (1, 'admin', '01', 1, 'SMS 기간계', NULL, NULL, 'R', NULL, NULL, '20180419', '000000', 'Y', 0, NULL, 1, NULL, NULL, NULL, NULL, 1, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'S', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 1, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, NULL, NULL, NULL, 0, 'N', NULL, 1, 0, 1, 0);
INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (2, 'admin', '01', 1, 'LMS/MMS 기간계', NULL, 'LMS 발송 테스트', 'R', NULL, NULL, '20180419', '000000', 'Y', 3, NULL, 1, NULL, NULL, NULL, NULL, 2, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'T', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 2, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, NULL, NULL, NULL, 0, 'N', NULL, 1, 0, 1, 0);
INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (3, 'admin', '01', 1, '알림톡 기간계', NULL, NULL, 'R', NULL, NULL, '20180419', '000000', 'Y', 0, NULL, 1, NULL, NULL, NULL, NULL, 3, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'A', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 3, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, '0156eb72408d4ba4c732c72a904d605219aa36a5', '0156eb72408d4ba4c732c72a904d605219aa36a5', 'mnwise_1801_0001', 0, 'Y', '실패시 우회발송', 1, 0, 1, 0);
INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (4, 'admin', '01', 1, '친구톡 기간계', NULL, NULL, 'R', NULL, NULL, '20180419', '000000', 'Y', 3, NULL, 1, NULL, NULL, NULL, NULL, 4, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'C', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 4, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, NULL, '0156eb72408d4ba4c732c72a904d605219aa36a5', NULL, 0, 'N', NULL, 2, 0, 1, 0);
INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (5, 'admin', '01', 1, 'SMS 단건 발송', NULL, NULL, 'R', NULL, NULL, '20180417', '000000', 'Y', 0, NULL, 1, NULL, NULL, NULL, NULL, 5, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'S', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 5, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, NULL, 0, NULL, NULL, NULL, 0, 'N', NULL, 1, 0, 1, 0);
INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (6, 'admin', '01', 1, 'LMS/MMS 단건 발송', NULL, NULL, 'R', NULL, NULL, '20180419', '000000', 'Y', 3, NULL, 1, NULL, NULL, NULL, NULL, 6, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'T', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 6, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, NULL, NULL, NULL, 0, 'N', NULL, 1, 0, 1, 0);
INSERT INTO NVECAREMSG
(ECARE_NO, USER_ID, GRP_CD, SEGMENT_NO, ECARE_NM, ECARE_DESC, ECARE_PREFACE, ECARE_STS, CREATE_DT, CREATE_TM, LASTUPDATE_DT, LASTUPDATE_TM, CAMPAIGN_TYPE, TEMPLATE_TYPE, SENDING_STS, TARGET_CNT, SHARE_YN, MSGASSORT_CD, LOG_YN, KEEPDAY, ECMSCHEDULE_NO, SENDER_NM, SENDER_EMAIL, SENDING_MODE, RETRY_CNT, RECEIVER_NM, SENDER_TEL, RETMAIL_RECEIVER, ECARE_CLASS, RELATION_TYPE, CHANNEL_TYPE, HTMLMAKER_TYPE, SERVICE_TYPE, ACCOUNT_DT, ECARE_LEVEL, CATEGORY_CD, RESEND_YN, RESEND_CNT, RESEND_TM, SVC_ID, SUB_TYPE, SURVEY_END_YN, SURVEY_RESPONSE_CNT, SURVEY_NO, SURVEY_START_DT, SURVEY_START_TM, SURVEY_END_DT, SURVEY_END_TM, DEPTH_NO, EDITOR_ID, SCENARIO_NO, VERIFY_YN, VERIFY_GRP_CD, SEND_SERVER, BLOCK_YN, VERIFY_B4_SEND, DELETE_YN, SECURITY_MAIL_YN, REQ_DEPT_ID, REQ_USER_ID, RESEND_ECARE_NO, TEMPLATE_SENDER_KEY, KAKAO_SENDER_KEY, KAKAO_TMPL_CD, KAKAO_IMAGE_NO, FAILBACK_SEND_YN, FAILBACK_SUBJECT, TMPL_VER, COVER_VER, HANDLER_VER, PREFACE_VER)
VALUES (7, 'admin', '01', 1, '알림톡 단건발송', NULL, NULL, 'R', NULL, NULL, '20180419', '000000', 'Y', 0, NULL, 1, NULL, NULL, NULL, NULL, 7, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'A', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 7, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, '0156eb72408d4ba4c732c72a904d605219aa36a5', '0156eb72408d4ba4c732c72a904d605219aa36a5', 'mnwise_1801_0001', 0, 'N', NULL, 1, 0, 1, 0);
INSERT INTO nvecaremsg (ecare_no, user_id, grp_cd, segment_no, ecare_nm, ecare_desc, ecare_preface, ecare_sts, create_dt, create_tm, lastupdate_dt, lastupdate_tm, campaign_type, template_type, sending_sts, target_cnt, share_yn, msgassort_cd, log_yn, keepday, ecmschedule_no, sender_nm, sender_email, sending_mode, retry_cnt, receiver_nm, sender_tel, retmail_receiver, ecare_class, relation_type, channel_type, htmlmaker_type, service_type, account_dt, ecare_level, category_cd, resend_yn, resend_cnt, resend_tm, svc_id, sub_type, survey_end_yn, survey_response_cnt, survey_no, survey_start_dt, survey_start_tm, survey_end_dt, survey_end_tm, depth_no, editor_id, scenario_no, verify_yn, verify_grp_cd, send_server, block_yn, verify_b4_send, delete_yn, security_mail_yn, req_dept_id, req_user_id, resend_ecare_no, template_sender_key, kakao_sender_key, kakao_tmpl_cd, kakao_image_no, failback_send_yn, failback_subject, tmpl_ver, cover_ver, handler_ver, preface_ver)
VALUES (8, 'admin', '01', 1, '친구톡 단건발송', NULL, NULL, 'R', NULL, NULL, '20180419', '000000', 'Y', 3, NULL, 1, NULL, NULL, NULL, NULL, 8, 'mnwise', '', NULL, 1, NULL, '02-000-0000', '', 'A', NULL, 'C', NULL, 'S', NULL, '3', NULL, NULL, NULL, NULL, NULL, 'S', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'admin', 8, NULL, NULL, NULL, NULL, 'N', NULL, 'N', NULL, 'admin', 0, NULL, '0156eb72408d4ba4c732c72a904d605219aa36a5', NULL, 0, 'N', NULL, 2, 0, 1, 0);

INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (1, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (2, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (3, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (4, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (5, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (6, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (7, 'G', '11');
INSERT INTO nvecmsghandler (ecare_no, `type`, appsource) VALUES (8, 'G', '11');

INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (1, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (2, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (3, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (4, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (5, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (6, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (7, 'TRACE', NULL, NULL, NULL, NULL, '1');
INSERT INTO nvecaretraceinfo (ecare_no, trace_type, start_dt, start_tm, end_dt, end_tm, term_type) VALUES (8, 'TRACE', NULL, NULL, NULL, NULL, '1');

INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (1, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (2, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (3, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (4, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (5, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (6, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (7, ' ', '');
INSERT INTO nvecaretemplate (ecare_no, seg, template) VALUES (8, ' ', '');