-- 메뉴(영문)
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030106', '03', 1, 'Monthly statistics Sending', '/report/campaign/monthlyRpt.do', NULL, 'Y', 'report', 5, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030107', '03', 1, 'Departmental billing statistics', '/report/campaign/dept_stat.do', NULL, 'N', 'report', 6, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('05', NULL, 0, 'Segment', '/segment/segmentList.do', NULL, 'Y', 'segment', 5, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('07', NULL, 0, 'Setting', '/env/env.do', NULL, 'Y', 'env', 7, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0401', '04', 1, 'Template List', '/template/templateList.do', NULL, 'Y', 'template', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0701', '07', 1, 'Server Setting information', '/env/env.do', NULL, 'Y', 'env', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0707', '07', 1, 'The default handler settings', '/env/defaultHandlerList.do', NULL, 'Y', 'env', 7, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0703', '07', 1, 'Holiday Management', '/env/blockDate.do', NULL, 'Y', 'env', 3, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('03', NULL, 0, 'Report', '/report/campaign/campaignRptList.do', NULL, 'Y', 'report', 4, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('04', NULL, 0, 'Template', '/template/templateList.do', NULL, 'Y', 'template', 4, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('06', NULL, 0, 'User', '/account/accountDept.do', NULL, 'Y', 'account', 6, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0102', '01', 1, 'Campaign List', '/campaign/campaignList.do', NULL, 'Y', 'campaign', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0103', '01', 1, 'Campaign Registration', '/campaign/campaign1Step.do', NULL, 'Y', 'campaign', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0104', '01', 1, 'Campaign Customer History', '/campaign/campaignSendLog.do', NULL, 'Y', 'campaign', 3, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0201', '02', 1, 'eCare List', '/ecare/ecareList.do', NULL, 'Y', 'ecare', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0202', '02', 1, 'eCare Registration', '/ecare/ecare1Step.do', NULL, 'Y', 'ecare', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0203', '02', 1, 'eCare Customer History', '/ecare/ecareSendLog.do', NULL, 'Y', 'ecare', 3, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0402', '04', 1, 'Template Registration', '/template/templateReg.do', NULL, 'Y', 'template', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0702', '07', 1, 'DB Management', '/env/database.do', NULL, 'Y', 'env', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0704', '07', 1, 'Domain Management', '/env/domain.do', NULL, 'Y', 'env', 4, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0712', '07', 1, 'Personal Information Management', '/env/myInfo.do', NULL, 'Y', 'env', 6, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0705', '07', 1, 'Banned wordsManagement', '/env/badWord.do', NULL, 'Y', 'env', 5, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0710', '07', 1, 'Smtp Code Management', '/env/smtpCode.do', NULL, 'Y', 'env', 8, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0708', '07', 1, 'Batch handler Setting', '/env/schedulebatchlist.do', NULL, 'N', 'env', 9, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0501', '05', 1, 'Segment Reference', '/segment/segmentList.do', NULL, 'Y', 'segment', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0502', '05', 1, 'Segment Registration', '/segment/sqlSegment1Step.do', NULL, 'Y', 'segment', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0601', '06', 1, 'User Management', '/account/account_management.do', NULL, 'N', 'account', 7, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030203', '03', 1, 'Monthly statistics Sending', '/report/ecare/monthlyRpt.do', NULL, 'Y', 'report', 12, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030204', '03', 1, 'Departmental billing statistics', '/report/ecare/dept_stat.do', NULL, 'N', 'report', 13, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030201', '03', 1, 'eCare List', '/report/ecare/ecareRptList.do', NULL, 'Y', 'report', 10, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0403', '04', 1, 'Mobile Template List', '/template/mobileTemplateList.do', NULL, 'Y', 'template', 3, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0404', '04', 1, 'Mobile Template Registration', '/template/mobileTemplateReg.do', NULL, 'Y', 'template', 4, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('01', NULL, 0, 'Campaign', '/campaign/campaignList.do', NULL, 'Y', 'campaign', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('02', NULL, 0, 'eCare', '/ecare/ecareList.do', NULL, 'Y', 'ecare', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030101', '03', 1, 'Campaign List', '/report/campaign/campaignRptList.do', NULL, 'Y', 'report', 2, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('030105', '03', 1, 'A Comparative Analysis', '/report/campaign/compareRpt.do', NULL, 'Y', 'report', 4, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0504', '05', 1, 'Segment File Upload', '/segment/fileSegment1Step.do', NULL, 'Y', 'segment', 4, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0711', '07', 1, 'Message Sender Information', '/env/senderInfo.do', NULL, 'Y', 'env', 10, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0606', '06', 1, 'Department Management', '/account/accountDept.do', NULL, 'Y', 'account', 1, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0607', '06', 1, 'User Management', '/account/accountUser.do', NULL, 'Y', 'account', 3, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0608', '06', 1, 'Department Permission Management', '/account/accountDeptRole.do', NULL, 'Y', 'account', 2, 'M');
INSERT INTO NVMENU ( MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0714', '07', 1, 'Log Management', '/env/logFileList.do', NULL, 'Y', 'env', 13, 'M');
INSERT INTO NVMENU ( MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0715', '07', 1, 'PUSH Setting','/env/pushSetUp.do', NULL, 'Y', 'env', 14, 'M');

-- TAG 초기값
INSERT INTO NVCAMPTAG (TAG_NO,TAG_NM) VALUES (1,'');
INSERT INTO NVECAREMSGTAG (TAG_NO,TAG_NM) VALUES (1,'');
INSERT INTO NVSEGMENTTAG (TAG_NO,TAG_NM) VALUES (1,'');
INSERT INTO NVCONTENTSTAG (TAG_NO,TAG_NM) VALUES (1,'');
INSERT INTO NVMOBILECONTENTSTAG (TAG_NO,TAG_NM) VALUES (1,'');

-- 금칙어검사 초기값
INSERT INTO NVBADWORD (BAD_WORDS, CHANNEL_TYPE) VALUES ('','M');
INSERT INTO NVBADWORD (BAD_WORDS, CHANNEL_TYPE) VALUES ('','S,T,P');

-- 준실시간 DB 인터페이스 처리를 위한 기본 값 등록
INSERT INTO NVECAREMSG(ECARE_NO) VALUES (0);
INSERT INTO NVECMSGHANDLER(ECARE_NO) VALUES (0);

-- 유효수신구간
INSERT INTO NVDURATIONINFO( DURATIONINFO_CD, MAXTIME, MINTIME,VALID_CHK) VALUES ('01', 10, 10, 'Y');

-- 서버환경정보
INSERT INTO NVSERVERINFO (
    HOST_NM, PORT_NO, DRIVER_NM, DRIVER_DSN, DBUSER_ID,
    DBPASSWORD, OPENCLICK_PATH, SURVEY_PATH, LINK_PATH, HTMLMAKER_PATH,
    OPENIMAGE_PATH, DURATION_PATH, REJECT_PATH, SMTP_IP, SMTP_PORT,
    FULA_IP, FULA_PORT, FTP_YN, FTP_USER_ID, FTP_PASSWORD,
    LASTUPDATE_DT, EDITOR_ID, RET_DOMAIN, RETRY_CNT, B4_SEND_APPROVE_YN,
    B4_SEND_VERIFY_YN, B4_REAL_SEND_TEST_SEND_YN, ASE_LINK_MERGE_PARAM, ASE_REJECT_MERGE_PARAM, ASE_OPEN_SCRIPTLET,
    GROOVY_LINK_MERGE_PARAM, GROOVY_REJECT_MERGE_PARAM, GROOVY_OPEN_SCRIPTLET, RESEND_INCLUDE_RETURNMAIL_YN, RESEND_INCLUDE_MAIL_KEY_YN,
    RESEND_ERROR_CD, FAX_RESEND_ERROR_CD , SMS_RESEND_ERROR_CD , ALTALK_RESEND_ERROR_CD , PUSH_RESEND_ERROR_CD ,
    SPOOL_PRESERVE_PERIOD, LOG_PRESERVE_PERIOD, RESULT_FILE_DOWNLOAD_YN,
    SUCS_RESULT_FILE_DOWNLOAD_YN, KAKAO_TEMPLATE_LAST_SYNC_DTM
) VALUES (
    '1', NULL, NULL, NULL, NULL,
    NULL, 'http://127.0.0.1:9000/servlet/ReceiveConfirmEM', '', 'http://127.0.0.1:9000/servlet/LinkTraceEM', '',
    NULL, NULL, 'http://127.0.0.1:9000/servlet/RejectEM', NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, 1, 'N',
    'N', 'N', '?SEND_MODE=context.get("_SEND_MODE")&CAMPAIGN_NO=context.get("_CAMPAIGN_NO")&RESULT_SEQ=context.get("_RESULT_SEQ")&START_DATE=context.get("_START_DATE")&END_DATE=context.get("_END_DATE")&LIST_SEQ=context.get("_LIST_SEQ")&RECORD_SEQ=context.get("_RECORD_SEQ")&CUSTOMER_ID=context.getEncryptedString("_CUSTOMER_ID")', '?SEND_MODE=context.get("_SEND_MODE")&CAMPAIGN_NO=context.get("_CAMPAIGN_NO")&RESULT_SEQ=context.get("_RESULT_SEQ")&START_DATE=context.get("_START_DATE")&END_DATE=context.get("_END_DATE")&LIST_SEQ=context.get("_LIST_SEQ")&RECORD_SEQ=context.get("_RECORD_SEQ")&CUSTOMER_ID=context.getEncryptedString("_CUSTOMER_ID")', '?SEND_MODE=context.get("_SEND_MODE")&CAMPAIGN_NO=context.get("_CAMPAIGN_NO")&RESULT_SEQ=context.get("_RESULT_SEQ")&START_DATE=context.get("_START_DATE")&END_DATE=context.get("_END_DATE")&LIST_SEQ=context.get("_LIST_SEQ")&RECORD_SEQ=context.get("_RECORD_SEQ")&CUSTOMER_ID=context.getEncryptedString("_CUSTOMER_ID")',
    '?SEND_MODE=context.get("_SEND_MODE")&CAMPAIGN_NO=context.get("_CAMPAIGN_NO")&RESULT_SEQ=context.get("_RESULT_SEQ")&START_DATE=context.get("_START_DATE")&END_DATE=context.get("_END_DATE")&LIST_SEQ=context.get("_LIST_SEQ")&RECORD_SEQ=context.get("_RECORD_SEQ")&CUSTOMER_ID=context.getEncryptedString("_CUSTOMER_ID")', '?SEND_MODE=context.get("_SEND_MODE")&CAMPAIGN_NO=context.get("_CAMPAIGN_NO")&RESULT_SEQ=context.get("_RESULT_SEQ")&START_DATE=context.get("_START_DATE")&END_DATE=context.get("_END_DATE")&LIST_SEQ=context.get("_LIST_SEQ")&RECORD_SEQ=context.get("_RECORD_SEQ")&CUSTOMER_ID=context.getEncryptedString("_CUSTOMER_ID")&CUSTOMER_EMAIL=context.getEncryptedString("_CUSTOMER_EMAIL")', '?SEND_MODE=context.get("_SEND_MODE")&CAMPAIGN_NO=context.get("_CAMPAIGN_NO")&RESULT_SEQ=context.get("_RESULT_SEQ")&START_DATE=context.get("_START_DATE")&END_DATE=context.get("_END_DATE")&LIST_SEQ=context.get("_LIST_SEQ")&RECORD_SEQ=context.get("_RECORD_SEQ")&CUSTOMER_ID=context.getEncryptedString("_CUSTOMER_ID")', 'Y', 'N',
    '250,550,553,610,800', '250', '0,00000' , '0000', '250',
    '7', '7', 'Y', 'Y', ''
);