-- 배치 I/F 테이블
CREATE TABLE NVBATCH (
    SEQ                       VARCHAR2(100)       NOT NULL,
    ECARE_NO                  NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16,0),
    LIST_SEQ                  VARCHAR2(10),
    CHANNEL                   VARCHAR2(2)         NOT NULL,
    SVC_ID                    VARCHAR2(20),
    REQ_USER_ID               VARCHAR2(50),
    REQ_DEPT_ID               VARCHAR2(50),
    REQ_DT                    VARCHAR2(8)         NOT NULL,
    REQ_TM                    VARCHAR2(6)         NOT NULL,
    TMPL_TYPE                 CHAR(1)             NOT NULL,
    RECEIVER_ID               VARCHAR2(50)        NOT NULL,
    RECEIVER_NM               VARCHAR2(50)        NOT NULL,
    RECEIVER                  VARCHAR2(100)       NOT NULL,
    SENDER_NM                 VARCHAR2(50),
    SENDER                    VARCHAR2(100),
    SUBJECT                   VARCHAR2(250),
    SEND_FG                   CHAR(1)             DEFAULT 'R',
    SLOT1                     VARCHAR2(100),
    SLOT2                     VARCHAR2(100),
    SECU_KEY                  VARCHAR2(13),
    SECURITY_PATH             VARCHAR2(1000),
    ERROR_MSG                 VARCHAR2(250),
    RESERVED_DATE             VARCHAR2(14),
    PREVIEW_TYPE              CHAR(1)             DEFAULT 'N'    NOT NULL,
    DATA_CNT                  NUMERIC(3),
    FILE_PATH1                VARCHAR2(4000),
    FILE_PATH2                VARCHAR2(250),
    FILE_PATH3                VARCHAR2(250),
    SRFIDD                    VARCHAR2(50),
    JONMUN                    CLOB
);
ALTER TABLE NVBATCH ADD CONSTRAINT PK_NVBATCH PRIMARY KEY (SEQ);
CREATE INDEX IDX_NVBATCH_SEND_FG ON NVBATCH (SEND_FG, REQ_DT, REQ_TM);
CREATE INDEX IDX_NVBATCH_REQ_DT ON NVBATCH (REQ_DT, REQ_TM);
CREATE INDEX IDX_NVBATCH_ENO_RSEQ ON NVBATCH (ECARE_NO, RESULT_SEQ);
CREATE INDEX IDX_NVBATCH_RECEIVER ON NVBATCH (RECEIVER, REQ_DT, REQ_TM);

COMMENT ON TABLE  NVBATCH IS '스케줄대상자';
COMMENT ON COLUMN NVBATCH.SEQ IS '순번';
COMMENT ON COLUMN NVBATCH.ECARE_NO IS '이케어번호. wiseU 템플릿번호를 의미';
COMMENT ON COLUMN NVBATCH.RESULT_SEQ IS '결과순번. 발송시 LTS에서 업데이트';
COMMENT ON COLUMN NVBATCH.RECEIVER_ID IS '수신자ID. 개인식별키로 발송이력조회시 사용';
COMMENT ON COLUMN NVBATCH.LIST_SEQ IS '목록순번. 발송시 MTS에서 업데이트';
COMMENT ON COLUMN NVBATCH.CHANNEL IS '채널';
COMMENT ON COLUMN NVBATCH.SVC_ID IS '서비스ID. 레거시 템플릿번호';
COMMENT ON COLUMN NVBATCH.REQ_USER_ID IS '발송요청자ID';
COMMENT ON COLUMN NVBATCH.REQ_DEPT_ID IS '발송요청부서ID';
COMMENT ON COLUMN NVBATCH.REQ_DT IS '발송요청일자';
COMMENT ON COLUMN NVBATCH.REQ_TM IS '발송요청시간';
COMMENT ON COLUMN NVBATCH.TMPL_TYPE IS '템플릿타입';
COMMENT ON COLUMN NVBATCH.RECEIVER_NM IS '수신자명';
COMMENT ON COLUMN NVBATCH.RECEIVER IS '수신자 메일주소/핸드폰번호/팩스번호';
COMMENT ON COLUMN NVBATCH.SENDER_NM IS '발신자명 (메일에 표시)';
COMMENT ON COLUMN NVBATCH.SENDER IS '발신자 메일주소/핸드폰번호/팩스번호';
COMMENT ON COLUMN NVBATCH.SUBJECT IS '(메일)제목';
COMMENT ON COLUMN NVBATCH.SEND_FG IS '발송여부플래그';
COMMENT ON COLUMN NVBATCH.JONMUN IS '전문내용/템플릿내용';
COMMENT ON COLUMN NVBATCH.SLOT1 IS '부가정보1';
COMMENT ON COLUMN NVBATCH.SLOT2 IS '부가정보2';
COMMENT ON COLUMN NVBATCH.SECU_KEY IS '보안키. 보안메일 생성시 사용';
COMMENT ON COLUMN NVBATCH.SECURITY_PATH IS '보안메일커버파일경로';
COMMENT ON COLUMN NVBATCH.ERROR_MSG IS '메일생성 에러메시지';
COMMENT ON COLUMN NVBATCH.RESERVED_DATE IS '발송예약일시';
COMMENT ON COLUMN NVBATCH.PREVIEW_TYPE IS '미리보기타입';
COMMENT ON COLUMN NVBATCH.DATA_CNT IS 'NVBATCHDATA 테이블에 저장된 레코드수';
COMMENT ON COLUMN NVBATCH.FILE_PATH1 IS '파일경로1';
COMMENT ON COLUMN NVBATCH.FILE_PATH2 IS '파일경로2';
COMMENT ON COLUMN NVBATCH.FILE_PATH3 IS '파일경로3';
COMMENT ON COLUMN NVBATCH.SRFIDD IS '팩스키';
COMMENT ON COLUMN NVBATCH.JONMUN IS '전문';


-- 발송취소 테이블
CREATE TABLE NVCANCEL(
    CAN_REQ_DTM VARCHAR2(14),
    CAN_SEQ     VARCHAR2(100),
    ORG_SEQ     VARCHAR2(100)   NOT NULL,
    ORG_REQ_DT  VARCHAR2(8)     NOT NULL,
    ECARE_NO    NUMBER(15)      NOT NULL,
    CAN_FG      VARCHAR2(1)     DEFAULT 'R',
    CAN_DTM     VARCHAR2(14),
    ACCEPT_DTM  VARCHAR2(14),
    RSLT_CD     VARCHAR2(1),
    RSLT_MSG    VARCHAR2(500)
);
ALTER TABLE NVCANCEL ADD CONSTRAINT PK_NVCANCEL PRIMARY KEY (CAN_REQ_DTM, CAN_SEQ);
CREATE INDEX IDX_NVCANCEL_CAN_FG ON NVCANCEL(CAN_FG);
CREATE INDEX IDX_NVCANCEL_ORG ON NVCANCEL(ORG_SEQ, ORG_REQ_DT);

COMMENT ON TABLE NVCANCEL IS '발송취소';
COMMENT ON COLUMN NVCANCEL.CAN_REQ_DTM IS '발송취소 요청일시';
COMMENT ON COLUMN NVCANCEL.CAN_SEQ IS '발송취소요청 일련번호';
COMMENT ON COLUMN NVCANCEL.ORG_SEQ IS 'I/F발송 시퀀스';
COMMENT ON COLUMN NVCANCEL.ORG_REQ_DT IS 'I/F발송 요청일자';
COMMENT ON COLUMN NVCANCEL.ECARE_NO IS '이케어 번호';
COMMENT ON COLUMN NVCANCEL.CAN_FG IS '취소요청 상태코드';
COMMENT ON COLUMN NVCANCEL.CAN_DTM IS '취소일시';
COMMENT ON COLUMN NVCANCEL.ACCEPT_DTM IS '처리접수 일시';
COMMENT ON COLUMN NVCANCEL.RSLT_CD IS '취소 결과코드';
COMMENT ON COLUMN NVCANCEL.RSLT_MSG IS '취소 결과메시지';

-- 옴니채널 시멘틱 추가

INSERT INTO NVSEMANTIC (SEGMENT_NO, FIELD_SEQ, FIELD_NM, FIELD_DESC, FIELD_TYPE, FIELD_LENGTH, INITVALUE, MINVALUE, MAXVALUE, NULL_YN, FIELD_KEY)
VALUES(-1, 4, 'RECEIVER_TEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'S');

--옴니채널사용 컬럼
ALTER TABLE NVRESENDTARGET ADD (TARGET_CONTACT2 VARCHAR2(100));

--발송취소이력 메뉴추가
INSERT INTO PUSH.NVMENU
(MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES('030206', '03', 1, '취소 요청 조회', '/ecare/cancel_list.do', NULL, 'Y', 'report', 15, 'M');
INSERT INTO PUSH.NVMENUROLE
(USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES('admin', '030206', 'R', 'W', NULL);
INSERT INTO PUSH.NVMENU_LANG
(MENU_CD, LANG, MENU_NM)
VALUES('030206', 'ko', '취소 요청 조회');


-- WATCHDOG (MTS) 취소건수 추가
ALTER TABLE NV_SVC_MTS ADD CANCEL_CNT NUMERIC(10);
COMMENT ON COLUMN NV_SVC_MTS.CANCEL_CNT IS '발송취소 건수';

-- 발송결과테이블 취소건수 추가
ALTER TABLE NVECARESENDRESULT ADD CANCEL_CNT NUMERIC(10);
COMMENT ON COLUMN NVECARESENDRESULT.CANCEL_CNT IS '발송취소 건수';

--누락된듯
ALTER TABLE NVECARERECEIPT      ADD     CLIENT_INFO  VARCHAR2(200);
ALTER TABLE NVECARERECEIPT      ADD     MOBILE_YN    VARCHAR2(1);

--문자 통계 추가
ALTER TABLE NVSMSRPTSENDRESULT      ADD     CANCEL_CNT  NUMBER(10,0);
COMMENT ON COLUMN NVSMSRPTSENDRESULT.CANCEL_CNT IS '취소수';