-- wiseU 7.2.7 -> 7.3.0 업그레이드 시 사용
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0407', '04', 1, '브랜드톡 리스트', '/template/brandtalkTemplateList.do', NULL, 'Y', 'template', 7, 'M');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES ('0407', 'ko', '브랜드톡 리스트');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0407', 'R', 'W', NULL);

INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0408', '04', 1, '브랜드톡 등록', '/template/brandtalkTemplateReg.do', NULL, 'Y', 'template', 8, 'M');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM)
VALUES ('0408', 'ko', '브랜드톡 등록');
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0408', 'R', 'W', NULL);


--테이블 추가
ALTER TABLE NVMOBILECONTENTS ADD CONTENT_TYPE VARCHAR2(10) ;
ALTER TABLE NVMOBILECONTENTS ADD UNSUBSCRIBE_CONTENT VARCHAR2(20);
ALTER TABLE NVMOBILECONTENTS ADD MESSAGE_TYPE   VARCHAR2(10);
ALTER TABLE NVMOBILECONTENTS MODIFY KAKAO_TMPL_CD VARCHAR2(50);
ALTER TABLE NVMOBILECONTENTS MODIFY CONTS_NM VARCHAR2(200);

--카카오 탬플릿 코드 변경(브랜드톡이 50자리)
ALTER TABLE NVCAMPAIGN MODIFY KAKAO_TMPL_CD VARCHAR2(50);
ALTER TABLE NVECAREMSG MODIFY KAKAO_TMPL_CD VARCHAR2(50);
ALTER TABLE NVKAKAORPTSENDRESULT MODIFY TMPL_CD VARCHAR2(50);


--브랜드톡 에러코드가 5자리
ALTER TABLE NVSENDLOG MODIFY ERROR_CD VARCHAR2(5);
ALTER TABLE NVECARESENDLOG MODIFY ERROR_CD VARCHAR2(5);
-- 문자/카카오톡 메세지 일부 저장
ALTER TABLE NVSENDLOG ADD PART_MESSAGE VARCHAR2(500);
ALTER TABLE NVECARESENDLOG ADD PART_MESSAGE VARCHAR2(500);
ALTER TABLE NVTESTSENDLOG ADD PART_MESSAGE VARCHAR2(500);
ALTER TABLE NVTESTECARESENDLOG ADD PART_MESSAGE VARCHAR2(500);
-- 대체발송여부/대체발송 결과코드
ALTER TABLE NVSENDLOG ADD FAIL_BACK_CHANNEL VARCHAR2(1);
ALTER TABLE NVECARESENDLOG ADD FAIL_BACK_CHANNEL VARCHAR2(1);
ALTER TABLE NVSENDLOG ADD FAIL_BACK_RESULT_CD VARCHAR2(5);
ALTER TABLE NVECARESENDLOG ADD FAIL_BACK_RESULT_CD VARCHAR2(5);
--대체발송 발송시간
ALTER TABLE NVSENDLOG ADD FAIL_BACK_SENDDTM VARCHAR2(14);
ALTER TABLE NVECARESENDLOG ADD FAIL_BACK_SENDDTM VARCHAR2(14);

--템플릿 코드 적재
ALTER TABLE NVSENDLOG ADD TMPL_CD VARCHAR2(50);
ALTER TABLE NVECARESENDLOG ADD TMPL_CD VARCHAR2(50);
ALTER TABLE NVTESTSENDLOG ADD TMPL_CD VARCHAR2(50);
ALTER TABLE NVTESTECARESENDLOG ADD TMPL_CD VARCHAR2(50);
-- 결과 코드추가
INSERT INTO NVSENDERR (ERROR_CD, ERROR_NM, ERROR_DESC, ERROR_SMS_DESC, CATEGORY_CD, CHANNEL_TYPE, SPAM_YN)
VALUES('900', NULL, '핸들러 오류', NULL, '0106', 'M', 'N');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AF0001', '900', 'AF00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AS0001', '900', 'AS00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AB0001', '900', 'AB00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AC0001', '900', 'AC00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AA0001', '900', 'AA00', '핸들러 오류', '핸들러 오류', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('AS0001', 'v', 'AS00', '발신자 번호 미등록', '발신자 번호 미등록', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');

COMMENT ON COLUMN NVECARESENDLOG.FAIL_BACK_CHANNEL      IS '우회발송채널';
COMMENT ON COLUMN NVECARESENDLOG.FAIL_BACK_RESULT_CD    IS '우회발송결과코드';
COMMENT ON COLUMN NVECARESENDLOG.FAIL_BACK_SENDDTM      IS '우회발송발송일시';
COMMENT ON COLUMN NVECARESENDLOG.PART_MESSAGE           IS '부분메시지';
COMMENT ON COLUMN NVMOBILECONTENTS.CONTENT_TYPE         IS '콘텐츠유형';
COMMENT ON COLUMN NVMOBILECONTENTS.MESSAGE_TYPE         IS '메시지유형';
COMMENT ON COLUMN NVSENDLOG.TMPL_CD IS '템플릿코드';
COMMENT ON COLUMN NVECARESENDLOG.TMPL_CD IS '템플릿코드';
COMMENT ON COLUMN NVTESTSENDLOG.TMPL_CD IS '템플릿코드';
COMMENT ON COLUMN NVTESTECARESENDLOG.TMPL_CD IS '템플릿코드';
-- 미사용 메뉴 삭제(접속로그,사용자로그,세션로그)
DELETE FROM NVMENU WHERE MENU_CD in('0603','0604','0605');
DELETE FROM NVMENU_LANG WHERE MENU_CD in('0603','0604','0605');
DELETE FROM NVMENUROLE WHERE MENU_CD in('0603','0604','0605');