-- 친구톡 템플릿코드 컬럼 사이즈 조정
ALTER TABLE MZFTSENDTRAN        MODIFY TMPL_CD VARCHAR2 (30);
ALTER TABLE MZFTSENDLOG         MODIFY TMPL_CD VARCHAR2 (30);

-- 친구톡 디폴트 설정 제거 (오라클 적용 불가)
-- ALTER TABLE MZFTSENDTRAN    MODIFY SERVICE_TYPE    VARCHAR2(2);
-- ALTER TABLE MZFTSENDTRAN    MODIFY SERVICE_NO      NUMBER(15,0);

-- View 문법 오류 수정
CREATE OR REPLACE FORCE VIEW VIEW_SMS_LOG (
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, TRAN_RSLT,
    TRAN_MSG, SMS_TYPE, SLOT1, SLOT2, SEQ, LIST_SEQ
) AS
SELECT
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, TRAN_RSLT,
    (CASE WHEN MMS_BODY IS NULL THEN TRAN_MSG ELSE MMS_BODY END) AS TRAN_MSG, TRAN_ETC3 AS SMS_TYPE, SLOT1, SLOT2, SEQ, LOG.LIST_SEQ
FROM EM_LOG LOG LEFT OUTER JOIN EM_TRAN_MMS MMS
ON LOG.TRAN_ETC4 = MMS.MMS_SEQ;