-- wiseU 5.12.0 -> 7.0.0 업그레이드 시 사용

ALTER TABLE NVCAMPAIGN                  ADD    RELATION_TREE                    VARCHAR2(100)    DEFAULT 'N';
ALTER TABLE NVSERVERINFO                ADD    KAKAO_TEMPLATE_LAST_SYNC_DTM     VARCHAR2(14);
ALTER TABLE NVMOBILECONTENTS            ADD    KAKAO_INSP_STATUS                VARCHAR2(3);
ALTER TABLE NVMOBILECONTENTS            ADD    KAKAO_TMPL_STATUS                CHAR(1);
ALTER TABLE NVMOBILECONTENTS            ADD    USE_YN                           CHAR(1)    DEFAULT 'Y'    NOT NULL;
ALTER TABLE NVMOBILECONTENTS            ADD    CATEGORY_CD                      VARCHAR2(12);
ALTER TABLE NVECAREMSG                  ADD    TEMPLATE_SENDER_KEY              VARCHAR2(40);
ALTER TABLE NVECAREMSG                  ADD    FAILBACK_SEND_YN                 CHAR(1)    DEFAULT 'N';
ALTER TABLE NVECAREMSG                  ADD    FAILBACK_SUBJECT                 VARCHAR2(100);
ALTER TABLE NVECAREMSG                  ADD    KAKAO_IMAGE_NO                   NUMERIC(15)    DEFAULT 0;

ALTER TABLE NVMOBILECONTENTS            ADD    IMAGE_URL                        VARCHAR2(500);
ALTER TABLE NVMOBILECONTENTS            ADD    DETOUR_FILE_PATH                 VARCHAR2(250);
ALTER TABLE NVMOBILECONTENTS            ADD    DETOUR_FILE_NAME                 VARCHAR2(100);
ALTER TABLE NVMOBILECONTENTS            ADD    DETOUR_PREVIEW_PATH              VARCHAR2(250);
ALTER TABLE NVMOBILECONTENTS            ADD    DETOUR_PREVIEW_NAME              VARCHAR2(100);

ALTER TABLE NVECAREMSG                  MODIFY KAKAO_TMPL_CD                    VARCHAR2(30);
ALTER TABLE NVMOBILECONTENTS            MODIFY KAKAO_TMPL_CD                    VARCHAR2(30);

UPDATE      NVRPTDURATION               SET    RESULT_SEQ = 0 WHERE RESULT_SEQ IS NULL;
UPDATE      NVRPTOPEN                   SET    RESULT_SEQ = 0 WHERE RESULT_SEQ IS NULL;
UPDATE      NVRPTLINKDISTINCT           SET    RESULT_SEQ = 0 WHERE RESULT_SEQ IS NULL;
UPDATE      NVRPTLINK                   SET    RESULT_SEQ = 0 WHERE RESULT_SEQ IS NULL;

ALTER TABLE NVSMSRPTSENDRESULT          MODIFY SEND_GBN                         VARCHAR2(3)    NOT NULL;
ALTER TABLE NVRPTDURATION               MODIFY RESULT_SEQ                       NUMERIC(16)    NOT NULL;
ALTER TABLE NVRPTLINK                   MODIFY RESULT_SEQ                       NUMERIC(16)    NOT NULL;
ALTER TABLE NVRPTLINKDISTINCT           MODIFY RESULT_SEQ                       NUMERIC(16)    NOT NULL;
ALTER TABLE NVRPTOPEN                   MODIFY RESULT_SEQ                       NUMERIC(16)    NOT NULL;

ALTER TABLE NVCAMPAIGN                  MODIFY AB_TEST_TYPE                     CHAR(1) DEFAULT 'N';
ALTER TABLE NVCAMPAIGN                  MODIFY RELATION_TYPE                    CHAR(1) DEFAULT 'N';

ALTER TABLE NVSMSRPTSENDRESULT          DROP   CONSTRAINT PK_NVSMSRPTSENDRESULT;
ALTER TABLE NVSMSRPTSENDRESULT          ADD    CONSTRAINT PK_NVSMSRPTSENDRESULT PRIMARY KEY (REPORT_DT, SERVICE_NO, RESULT_SEQ, SERVICE_TYPE, SEND_GBN);

DROP  INDEX IDX_NVECARERETURNMAIL_RDT_RTM;

UPDATE NVMENU SET MENU_NM = '로그인 이력' WHERE MENU_CD = '0604';
UPDATE NVMENU_LANG SET MENU_NM = '로그인 이력' WHERE MENU_CD = '0604' AND LANG = 'ko';
UPDATE NV_CD_MST SET CD_DESC = '성공' WHERE CD_CAT = 'AC0001' AND CD =  '0000' AND LANG = 'ko';

-- 카카오 프로필 데이터
CREATE TABLE NVKAKAOPROFILE (
    USER_ID                   VARCHAR2(15)        NOT NULL,
    KAKAO_SENDER_KEY          VARCHAR2(40)        NOT NULL,
    KAKAO_YELLOW_ID           VARCHAR2(50)        NOT NULL,
    LAST_SYNC_DTM             VARCHAR2(14)
);
ALTER TABLE NVKAKAOPROFILE ADD CONSTRAINT PK_NVKAKAOPROFILE PRIMARY KEY (USER_ID, KAKAO_SENDER_KEY);

-- 알림톡/친구톡 발송통계
CREATE TABLE NVKAKAORPTSENDRESULT(
    REPORT_DT                 CHAR(8)             NOT NULL,
    SERVICE_NO                NUMERIC(15)         NOT NULL,
    RESULT_SEQ                NUMERIC(16)         NOT NULL,
    SERVICE_TYPE              CHAR(2)             NOT NULL,
    REQ_DEPT_ID               VARCHAR2(50)        NOT NULL,
    TMPL_CD                   VARCHAR(30)         DEFAULT 'FT'    NOT NULL,
    TARGET_CNT                NUMERIC(10),
    SEND_CNT                  NUMERIC(10),
    SUCCESS_CNT               NUMERIC(10),
    FAIL_CNT                  NUMERIC(10),
    SMS_TARGET_CNT            NUMERIC(10),
    SMS_SEND_CNT              NUMERIC(10),
    SMS_SUCCESS_CNT           NUMERIC(10),
    SMS_FAIL_CNT              NUMERIC(10),
    LMS_TARGET_CNT            NUMERIC(10),
    LMS_SEND_CNT              NUMERIC(10),
    LMS_SUCCESS_CNT           NUMERIC(10),
    LMS_FAIL_CNT              NUMERIC(10),
    MMS_TARGET_CNT            NUMERIC(10),
    MMS_SEND_CNT              NUMERIC(10),
    MMS_SUCCESS_CNT           NUMERIC(10),
    MMS_FAIL_CNT              NUMERIC(10),
    SEND_GBN                  VARCHAR2(3)         NOT NULL,
    SEND_TM                   CHAR(6)             NOT NULL
);
ALTER TABLE NVKAKAORPTSENDRESULT ADD CONSTRAINT PK_NVKAKAORPTSENDRESULT PRIMARY KEY (REPORT_DT, SERVICE_NO, RESULT_SEQ, SERVICE_TYPE,REQ_DEPT_ID, TMPL_CD);
CREATE INDEX IDX_NVKAKAKORPT_SNO_SGB ON NVKAKAORPTSENDRESULT (SERVICE_NO, SEND_GBN);
CREATE INDEX IDX_NVKAKAKORPT_SNO_RSQ ON NVKAKAORPTSENDRESULT (SERVICE_NO, RESULT_SEQ);
CREATE INDEX IDX_NVKAKAKORPT_SNO_STP ON NVKAKAORPTSENDRESULT (SERVICE_NO, SERVICE_TYPE);

INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE) VALUES ('0205', '02', 1, '단건발송', '/ecare/send_once.do', NULL, 'N', 'ecare', 5, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE) VALUES ('0405', '04', 1, '알림톡 템플릿 리스트', '/template/alimtalkTemplate.do', NULL, 'Y', 'template', 5, 'M');
INSERT INTO NVMENU (MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE) VALUES ('0406', '04', 1, '알림톡 템플릿 등록', '/template/alimtalkTemplateReg.do', NULL, 'Y', 'template', 6, 'M');

INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM) VALUES ('0205', 'ko', '단건발송');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM) VALUES ('0405', 'ko', '알림톡 템플릿 리스트');
INSERT INTO NVMENU_LANG (MENU_CD, LANG, MENU_NM) VALUES ('0406', 'ko', '알림톡 템플릿 등록');

INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH) VALUES ('admin', '0205', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH) VALUES ('admin', '0405', 'R', 'W', NULL);
INSERT INTO NVMENUROLE (USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH) VALUES ('admin', '0406', 'R', 'W', NULL);

UPDATE NVMENU_LANG SET MENU_NM = '템플릿 리스트' WHERE MENU_CD = '0401' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '템플릿 등록' WHERE MENU_CD = '0402' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '모바일 템플릿 리스트' WHERE MENU_CD = '0403' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '모바일 템플릿 등록' WHERE MENU_CD = '0404' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '대상자 조회' WHERE MENU_CD = '0501' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '대상자 등록' WHERE MENU_CD = '0502' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '하위 대상자 등록' WHERE MENU_CD = '0503' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '대상자 파일 올리기' WHERE MENU_CD = '0504' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '사용자 관리' WHERE MENU_CD = '0601' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '권한 관리' WHERE MENU_CD = '0602' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '접속 로그' WHERE MENU_CD = '0603' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '사용자 로그' WHERE MENU_CD = '0604' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '부서 로그' WHERE MENU_CD = '0605' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '서버 환경정보' WHERE MENU_CD = '0701' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = 'DB 관리' WHERE MENU_CD = '0702' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '공휴일 관리' WHERE MENU_CD = '0703' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '도메인 관리' WHERE MENU_CD = '0704' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '금칙어 관리' WHERE MENU_CD = '0705' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '서비스 연동 관리' WHERE MENU_CD = '0706' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '기본 핸들러 설정' WHERE MENU_CD = '0707' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '배치 핸들러 설정' WHERE MENU_CD = '0708' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '코드 관리' WHERE MENU_CD = '0710' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '개인정보 관리' WHERE MENU_CD = '0712' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '이케어 이력 관리' WHERE MENU_CD = '0713' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '설문 리스트' WHERE MENU_CD = '0801' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '설문 등록' WHERE MENU_CD = '0802' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '로그 관리' WHERE MENU_CD = '0714' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '알림톡 템플릿 리스트' WHERE MENU_CD = '0405' AND   LANG = 'ko';
UPDATE NVMENU_LANG SET MENU_NM = '알림톡 템플릿 등록' WHERE MENU_CD = '0406' AND   LANG = 'ko';

-- 알림톡 사용하는 환경에서만 실행
DELETE FROM NV_CD_MST WHERE CD_CAT = 'AA0001' AND CD IN ('1008', '1009', '1010', '1011', '2003', '2004', '3005', '3014', '3018', '3019', '3020', '3022', '9998', '9999', '999', '888');

INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA001', '-', '00', '알림톡 템플릿', '알림톡 템플릿 관련 코드', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA011', 'REG', 'KA01', '등록', '등록', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA011', 'REQ', 'KA01', '심사 요청', '심사 요청', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA011', 'APR', 'KA01', '승인', '승인', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA011', 'REJ', 'KA01', '반려', '반려', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA012', 'S', 'KA01', '중단', '중단', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA012', 'A', 'KA01', '정상', '정상', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA012', 'R', 'KA01', '대기', '대기', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA013', 'INQ', 'KA01', '문의', '문의', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA013', 'REP', 'KA01', '답변', '답변', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA013', 'APR', 'KA01', '승인', '승인', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('KA013', 'REJ', 'KA01', '반려', '반려', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('100221', 'S', '10022', '성공', '성공', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('100221', 'F', '10022', '실패', '실패', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('100221', 'O', '10022', '오픈', '오픈', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('5001', '-', '00', '템플릿관련', '템플릿관련', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('50011', '-', '5001', '템플릿카테고리', '템플릿카테고리', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('500111', 'SYS', '50011', '시스템 메시지', '시스템 메시지', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('500111', 'USR', '50011', '사용자 메시지', '시스템 메시지', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '888', 'AA00', 'UnknownErrorException', '카카오톡 서버로부터 정상적인 응답 혹은 발송 결과 응답을 받지 못한 경우', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 35, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '910', 'AA00', 'data format', '유효하지 않은 형식의 값을 입력 함', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 34, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '999', 'AA00', 'TimeoutExcetpion', '카카오톡 서버로부터 정상적인 응답 혹은 발송 결과 응답을 받지 못한 경우', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 34, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1011', 'AA00', 'ContractNotFound', '계약정보를 찾을 수 없음. (메시지 사업 담당자에게 문의)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1012', 'AA00', 'InvalidUserKeyException', '잘못된 형식의 유저키 요청', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1021', 'AA00', 'BlockedProfile', '차단 상태의 플러스친구 (플러스친구 운영툴에서 확인)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1022', 'AA00', 'DeactivatedProfile', '닫힘 상태의 플러스친구 (플러스친구 운영툴에서 확인)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1023', 'AA00', 'DeletedProfile', '삭제된 플러스친구 (플러스친구 운영툴에서 확인)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1024', 'AA00', 'DeletingProfile', '삭제대기 상태의 플러스친구 (플러스친구 운영툴에서 확인)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1025', 'AA00', 'SpammedProfile', '메시지차단 상태의 플러스친구 (플러스친구 운영툴에서 확인)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '1030', 'AA00', 'InvalidParameterException', '잘못된 파라메터 요청', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 12, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '2003', 'AA00', 'FailedToSendMessageByNoFriendshipException', '메시지 전송 실패(테스트 서버에서 친구관계가 아닌 경우)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 13, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '2004', 'AA00', 'FailedToMatchTemplateException', '템플릿 일치 확인시 오류 발생 (내부 오류 발생)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 14, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '3005', 'AA00', 'AckTimeoutException', '메시지를 발송했으나 10초 이내에 고객 단말기로부터 ACK 수신을 받지못한 경우', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 16, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '3014', 'AA00', 'MessageLengthOverLimitException', '메시지 길이 제한 오류 (템플릿별 제한 길이 또는 1000자 초과)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 23, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '3018', 'AA00', 'NoSendAvaliableStatusException', '메시지를 전송할 수 없음', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 26, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '9998', 'AA00', 'DoNotServiceExcetpion', '시스템에 문제가 발생하여 담당자가 확인하고 있는 경우', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 32, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG) VALUES ('AA0001', '9999', 'AA00', 'SystemErrorExcetpion', '시스템에 문제가 발생하여 담당자가 확인하고 있는 경우', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 33, 'ko');

-- SMS 사용하는 환경에서만 실행
DELETE FROM NV_CD_MST WHERE CD_CAT = 'AS0001' AND CD IN ('f', 'l', 'm');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('AS0001', 'f', 'AS00', '중계사 자체 형식 오류', '중계사 자체 형식 오류', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('AS0001', 'l', 'AS00', '중계사에서 spam 처리한건', 'www.nospan.go.kr에 등록된 번호에 대해 중계사에서 spam 처리한건', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG) VALUES ('AS0001', 'm', 'AS00', '중계사에서 Span 처리한건', '중계사에서 실패처리함', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');

CREATE OR REPLACE VIEW V_SMS_SUCCESS_FILE_LOG (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
) AS
SELECT
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_ETC3 AS TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
FROM EM_LOG
WHERE TRAN_RSLT = '0';

CREATE OR REPLACE VIEW V_SMS_FAIL_FILE_LOG (
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
) AS
SELECT
    TRAN_ID, TRAN_PHONE, TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, TRAN_STATUS, TRAN_MSG, TRAN_CALLBACK,
    SERVICE_NO, RESULT_SEQ, SLOT1, SLOT2, TRAN_ETC3 AS TRAN_TYPE, REQ_USER_ID, SEQ, LIST_SEQ, REQ_DEPT_ID
FROM EM_LOG
WHERE TRAN_RSLT <> '0';

CREATE OR REPLACE VIEW V_SMS_ERROR_RESULT (
    TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ, SEQ
) AS
SELECT
    TO_CHAR(TRAN_DATE,'YYYYMMDD') TRAN_DATE, TRAN_RSLT, SERVICE_TYPE, SERVICE_NO, RESULT_SEQ, SEQ
FROM EM_LOG
WHERE TRAN_RSLT NOT IN ('0');

CREATE OR REPLACE VIEW VIEW_SMS_LOG (
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, TRAN_RSLT,
    TRAN_MSG, SMS_TYPE, SLOT1, SLOT2, SEQ
) AS
SELECT
    TRAN_PHONE, TRAN_CALLBACK, TRAN_RSLTDATE, REQ_USER_ID, TRAN_RSLT,
    (CASE WHEN MMS_BODY IS NULL THEN TRAN_MSG ELSE MMS_BODY END) AS TRAN_MSG, TRAN_ETC3 AS SMS_TYPE, SLOT1, SLOT2, SEQ
FROM EM_LOG LOG LEFT OUTER JOIN EM_TRAN_MMS MMS
ON LOG.TRAN_ETC4 = MMS.MMS_SEQ;


/*==========================[PUSH]=============================*/

-- 금칙어 검사
UPDATE NVBADWORD SET CHANNEL_TYPE = 'S,T,P' WHERE CHANNEL_TYPE = 'S,T';

/*=============[channel]================*/
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('100211', 'P', '10021', 'PUSH', 'PUSH', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');
INSERT INTO NV_CD_MST(CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_COL, USE_YN, REG_DTM, MOD_DTM, CD_ORD, LANG)
VALUES ('C00031', 'P', 'C0003', 'PUSH', 'PUSH', NULL, 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL, NULL, 'ko');

/*=============[error code]================*/
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP00', '-', '00', 'PUSH 공통 결과코드', 'PUSH에서 사용하는 공통 결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

-- 코드별 카테고리
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001', '-', 'AP00', '정상 결과코드', '정상  결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '-', 'AP00', '시스템 에러 결과코드', '시스템 에러 결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003', '-', 'AP00', 'APNS 에러 결과코드', 'APNS 에러 결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004', '-', 'AP00', 'HTTP 에러 결과코드', 'HTTP 에러 결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005', '-', 'AP00', 'GCM 에러 결과코드', 'PUSH 에러 결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0006', '-', 'AP00', '기타 에러 결과코드', '기타 에러 결과코드', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

-- 엠앤와이즈 기본코드
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001', '250', 'AP0001', '발송요청 성공', '발송요청 성공', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '550', 'AP0002', '수신자 정보 없음(앱미설치 등)', '수신자 정보 없음(앱미설치 등)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '554', 'AP0002', '발송요청 실패', '발송요청 실패', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '700', 'AP0002', '통신실패', '통신실패', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '701', 'AP0002', 'IOException', 'IOException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '702', 'AP0002', '응답 코드의 길이가 3 미만', '응답 코드의 길이가 3 미만', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002', '703', 'AP0002', '명령어 전송 또는 응답 코드를 기다리는 중 IOException', '명령어 전송 또는 응답 코드를 기다리는 중 IOException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0006', '704', 'AP0006', 'Time Out, Interrupted Exception', 'Time Out, Interrupted Exception', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0006', '800', 'AP0006', 'Invalid Address', 'Invalid Address', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0006', '888', 'AP0006', 'Etc', 'Etc', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

/*=============[MENU]================*/
-- PUSH 설정
INSERT INTO NVMENU ( MENU_CD, PMENU_CD, LEVEL_NO, MENU_NM, MENU_LINK_URL, MENU_ICON_IMG, ACTIVE_YN, MODULE_NM, SORT_NO, M_TYPE)
VALUES ('0715', '07', 1, 'PUSH 설정','/env/env_push_setting.do', NULL, 'Y', 'env', 14, 'M');

INSERT INTO NVMENUROLE ( USER_ID, MENU_CD, READ_AUTH, WRITE_AUTH, EXECUTE_AUTH)
VALUES ('admin', '0715', 'R', 'W', NULL);
commit;

/*=============[MENU LANG]================*/
INSERT INTO NVMENU_LANG ( MENU_CD, LANG, MENU_NM)
VALUES ('0715', 'ko', 'PUSH 설정');

/**********************************/
/* Table Name: PUSH서비스정보 */
/**********************************/
CREATE TABLE NVPUSHSERVICEINFO(
        SVC_TYPE                            VARCHAR2(1)      NOT NULL,
        SVC_NO                              NUMERIC(15)       NOT NULL,
        PUSH_APP_ID                         VARCHAR2(20)     NOT NULL,
        PUSH_MSG_TYPE                       VARCHAR2(2)      NULL ,
        PUSH_MENU_ID                        VARCHAR2(6),
        PUSH_POP_IMG_USE                    VARCHAR2(1)      DEFAULT 'N'         NOT NULL,
        PUSH_IMG_URL                        VARCHAR2(500)    NULL ,
        PUSH_POP_BIG_IMG_USE                VARCHAR2(1)      DEFAULT 'N'         NOT NULL,
        PUSH_BIG_IMG_URL                    VARCHAR2(500)    NULL ,
        PUSH_CLICK_LINK                     VARCHAR2(500)    NULL
);

COMMENT ON TABLE NVPUSHSERVICEINFO is 'PUSH서비스정보';
COMMENT ON COLUMN NVPUSHSERVICEINFO.SVC_TYPE is '서비스구분';
COMMENT ON COLUMN NVPUSHSERVICEINFO.SVC_NO is '서비스NO';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_APP_ID is 'PUSH_APP_ID';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_MSG_TYPE is 'PUSH메시지유형';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_MENU_ID is 'PUSH메뉴ID';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_POP_IMG_USE is '팝업이미지사용유무';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_IMG_URL is '이미지';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_POP_BIG_IMG_USE is '팝업큰이미지사용유무';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_BIG_IMG_URL is '큰이미지';
COMMENT ON COLUMN NVPUSHSERVICEINFO.PUSH_CLICK_LINK is 'PUSH 클릭 링크';

ALTER TABLE NVPUSHSERVICEINFO ADD CONSTRAINT IDX_NVPUSHSERVICEINFO_PK PRIMARY KEY (SVC_TYPE, SVC_NO);

/**********************************/
/* Table Name: PUSH 앱 관리 */
/**********************************/
CREATE TABLE NVPUSHAPP(
        PUSH_APP_ID                         VARCHAR2(20)     NOT NULL,
        PUSH_APP_NM                         VARCHAR2(100)    NOT NULL,
        USE_YN                              VARCHAR2(1)      DEFAULT 'Y'         NOT NULL,
        INS_DTS                             VARCHAR2(14)     NULL ,
        INS_ID                              VARCHAR2(50)     NULL ,
        UPD_DTS                             VARCHAR2(14)     NULL ,
        UPD_ID                              VARCHAR2(50)     NULL
);

COMMENT ON TABLE NVPUSHAPP is 'PUSH 앱 관리';
COMMENT ON COLUMN NVPUSHAPP.PUSH_APP_ID is 'PUSH 앱 ID';
COMMENT ON COLUMN NVPUSHAPP.PUSH_APP_NM is 'PUSH 앱 이름';
COMMENT ON COLUMN NVPUSHAPP.USE_YN is '사용여부';
COMMENT ON COLUMN NVPUSHAPP.INS_DTS is '등록일시';
COMMENT ON COLUMN NVPUSHAPP.INS_ID is '등록자ID';
COMMENT ON COLUMN NVPUSHAPP.UPD_DTS is '수정일시';
COMMENT ON COLUMN NVPUSHAPP.UPD_ID is '수정자ID';

ALTER TABLE NVPUSHAPP ADD CONSTRAINT IDX_NVPUSHAPP_PK PRIMARY KEY (PUSH_APP_ID);

-- ALTER TABLE
ALTER TABLE NVSENDLOG ADD OPEN_DT VARCHAR2(14);
ALTER TABLE NVSENDLOG ADD EAI_SEND_FG VARCHAR2(1) DEFAULT 'N' NOT NULL;
CREATE INDEX IDX_NVSENDLOG_SDT_EFG ON NVSENDLOG (SEND_DT, EAI_SEND_FG);

ALTER TABLE NVRECEIPT ADD LOG_SEND_FG VARCHAR2(1) DEFAULT 'N';

ALTER TABLE NVECARESENDLOG ADD OPEN_DT VARCHAR2(14);
ALTER TABLE NVECARESENDLOG ADD EAI_SEND_FG VARCHAR2(1) DEFAULT 'N' NOT NULL;
CREATE INDEX IDX_NVECARESENDLOG_SDT_EFG ON NVECARESENDLOG (SEND_DT, EAI_SEND_FG);

ALTER TABLE NVECARERECEIPT add LOG_SEND_FG VARCHAR2(1) DEFAULT 'N';
