/*
-------------------------------------------------------------------------------
-- DBRO 제품 테이블
-------------------------------------------------------------------------------
*/

CREATE TABLE EM_LOG
(
    TRAN_PR          NUMBER(11)          NOT NULL,
    TRAN_REFKEY      VARCHAR2(40),
    TRAN_ID          VARCHAR2(20),
    TRAN_PHONE       VARCHAR2(32)        NOT NULL,
    TRAN_CALLBACK    VARCHAR2(32),
    TRAN_STATUS      CHAR(1),
    TRAN_DATE        DATE                NOT NULL,
    TRAN_RSLTDATE    DATE,
    TRAN_REPORTDATE  DATE,
    TRAN_RSLT        CHAR(1),
    TRAN_NET         VARCHAR2(3),
    TRAN_MSG         VARCHAR2(255),
    TRAN_ETC1        VARCHAR2(64),
    TRAN_ETC2        VARCHAR2(16),
    TRAN_ETC3        VARCHAR2(16),
    TRAN_ETC4        NUMBER(10),
    TRAN_TYPE        NUMBER(5)           NOT NULL
);

CREATE TABLE EM_TRAN
(
    TRAN_PR          NUMBER(11)          NOT NULL,
    TRAN_REFKEY      VARCHAR2(40),
    TRAN_ID          VARCHAR2(20),
    TRAN_PHONE       VARCHAR2(32)        NOT NULL,
    TRAN_CALLBACK    VARCHAR2(32),
    TRAN_STATUS      CHAR(1),
    TRAN_DATE        DATE                NOT NULL,
    TRAN_RSLTDATE    DATE,
    TRAN_REPORTDATE  DATE,
    TRAN_RSLT        CHAR(1),
    TRAN_NET         VARCHAR2(3),
    TRAN_MSG         VARCHAR2(255),
    TRAN_ETC1        VARCHAR2(64),
    TRAN_ETC2        VARCHAR2(16),
    TRAN_ETC3        VARCHAR2(16),
    TRAN_ETC4        NUMBER(10),
    TRAN_TYPE        NUMBER(5)           NOT NULL
);
ALTER TABLE EM_TRAN ADD CONSTRAINT PK_TRAN_PR PRIMARY KEY (TRAN_PR);
CREATE INDEX IDX_EM_TRAN_01 ON EM_TRAN(TRAN_STATUS,TRAN_DATE);
CREATE SEQUENCE EM_TRAN_PR;

CREATE TABLE EM_TRAN_MMS
(
    MMS_SEQ        NUMBER(10)           NOT NULL,
    FILE_CNT       NUMBER               NOT NULL,
    BUILD_YN       CHAR(1),
    MMS_BODY       VARCHAR2(4000),
    MMS_SUBJECT    VARCHAR2(40),
    FILE_TYPE1     VARCHAR2(3),
    FILE_TYPE2     VARCHAR2(3),
    FILE_TYPE3     VARCHAR2(3),
    FILE_TYPE4     VARCHAR2(3),
    FILE_TYPE5     VARCHAR2(3),
    FILE_NAME1     VARCHAR2(100),
    FILE_NAME2     VARCHAR2(100),
    FILE_NAME3     VARCHAR2(100),
    FILE_NAME4     VARCHAR2(100),
    FILE_NAME5     VARCHAR2(100),
    SERVICE_DEP1   VARCHAR2(3),
    SERVICE_DEP2   VARCHAR2(3),
    SERVICE_DEP3   VARCHAR2(3),
    SERVICE_DEP4   VARCHAR2(3),
    SERVICE_DEP5   VARCHAR2(3),
    SKN_FILE_NAME  VARCHAR2(255)
);

ALTER TABLE EM_TRAN_MMS ADD CONSTRAINT PK_MMS_SEQ PRIMARY KEY (MMS_SEQ);
CREATE SEQUENCE EM_TRAN_MMS_SEQ;


/*
-------------------------------------------------------------------------------
-- WISEU 연동
-------------------------------------------------------------------------------
*/
-- WISEU 연동 기본 컬럼
ALTER TABLE EM_LOG    ADD REQ_DEPT_CD    VARCHAR2(20);
ALTER TABLE EM_LOG    ADD SERVICE_TYPE   CHAR(2);
ALTER TABLE EM_LOG    ADD SERVICE_NO     NUMBER(15);
ALTER TABLE EM_LOG    ADD RESULT_SEQ     NUMBER(16);
ALTER TABLE EM_LOG    ADD SEQ            VARCHAR2(100);
ALTER TABLE EM_LOG    ADD SVC_ID         VARCHAR2(20);
ALTER TABLE EM_LOG    ADD SLOT1          VARCHAR2(100);
ALTER TABLE EM_LOG    ADD SLOT2          VARCHAR2(100);
ALTER TABLE EM_LOG    ADD REQ_USER_ID    VARCHAR2(100);
ALTER TABLE EM_LOG    ADD REQ_DEPT_ID    VARCHAR2(50);
ALTER TABLE EM_LOG    ADD LIST_SEQ       VARCHAR2(10);

ALTER TABLE EM_TRAN    ADD REQ_DEPT_CD    VARCHAR2(20)    DEFAULT '#admin';
ALTER TABLE EM_TRAN    ADD SERVICE_TYPE   CHAR(2);
ALTER TABLE EM_TRAN    ADD SERVICE_NO     NUMBER(15);
ALTER TABLE EM_TRAN    ADD RESULT_SEQ     NUMBER(16);
ALTER TABLE EM_TRAN    ADD SEQ            VARCHAR2(100);
ALTER TABLE EM_TRAN    ADD SVC_ID         VARCHAR2(20);
ALTER TABLE EM_TRAN    ADD SLOT1          VARCHAR2(100);
ALTER TABLE EM_TRAN    ADD SLOT2          VARCHAR2(100);
ALTER TABLE EM_TRAN    ADD REQ_USER_ID    VARCHAR2(100);
ALTER TABLE EM_TRAN    ADD REQ_DEPT_ID    VARCHAR2(50);
ALTER TABLE EM_TRAN    ADD LIST_SEQ       VARCHAR2(10);

-- wiseMOKA 기능 개발 과정에 추가
ALTER TABLE EM_TRAN_MMS    ADD    LIST_SEQ           VARCHAR2(10);
ALTER TABLE EM_TRAN_MMS    ADD    RESULT_SEQ         NUMERIC(16);
ALTER TABLE EM_TRAN_MMS    ADD    RESULT_SEQ_PAGE    NUMERIC(5);
CREATE INDEX IDX_EM_TRAN_MMS_RSLT ON EM_TRAN_MMS (RESULT_SEQ, RESULT_SEQ_PAGE);

-- EM_LOG 테이블의 발송 결과를 wiseU NVSENDLOG, NVECARESENDLOG 테이블에 업데이트하는 작업 플래그
ALTER TABLE EM_LOG ADD SYNC_FLAG CHAR(1) DEFAULT 'N' NOT NULL;
CREATE INDEX IDX_EM_LOG_SYNC_FLAG ON EM_LOG (SYNC_FLAG);

-- SMS/LMS/MMS 재발송 시 사용
CREATE INDEX IDX_EMLOG_SRLS ON EM_LOG (SERVICE_NO, RESULT_SEQ, LIST_SEQ, SERVICE_TYPE);
CREATE INDEX IDX_EMLOG_TDT ON EM_LOG (TRAN_DATE);
