/****************************************************************
 * ALTER
 * DB암호화로 인한 사이즈 변경
 * SMS: 25 ->88  (->100)
 * 이메일:100 ->152 (->256)
 * 이름: 100 ->152 (->256)
*****************************************************************/

ALTER TABLE NVFILEUPLOAD          MODIFY CUSTOMER_TEL           VARCHAR2(100);

ALTER TABLE NVFILEUPLOAD          MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVFILEUPLOAD          MODIFY CUSTOMER_EMAIL         VARCHAR2(256);
ALTER TABLE NVFILEUPLOAD          MODIFY CUSTOMER_FAX           VARCHAR2(256);

ALTER TABLE NVSENDLOG 	          MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVSENDLOG	          MODIFY CUSTOMER_EMAIL         VARCHAR2(256);
ALTER TABLE NVTESTSENDLOG         MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVTESTSENDLOG         MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVECAREMSG            MODIFY RECEIVER_NM            VARCHAR2(256);
ALTER TABLE NVECAREMSG            MODIFY SENDER_TEL             VARCHAR2(100);
ALTER TABLE NVECAREMSG            MODIFY SENDER_EMAIL           VARCHAR2(256);
ALTER TABLE NVECAREMSG            MODIFY SENDER_NM              VARCHAR2(256);
ALTER TABLE NVECAREMSG 			  MODIFY RETMAIL_RECEIVER       VARCHAR2(256);

ALTER TABLE NVECAREMIMEINFOLOG    MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVECAREMIMEINFOLOG    MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVECARESENDLOG        MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVECARESENDLOG        MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVTESTECARESENDLOG    MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVTESTECARESENDLOG    MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVDBINFO              MODIFY DBPASSWORD             VARCHAR2(100);

ALTER TABLE NVTESTUSERPOOL        MODIFY TESTRECEIVER_EMAIL     VARCHAR2(256);
ALTER TABLE NVTESTUSERPOOL        MODIFY TESTRECEIVER_NM        VARCHAR2(256);
ALTER TABLE NVTESTUSERPOOL        MODIFY TESTRECEIVER_TEL       VARCHAR2(100);
ALTER TABLE NVTESTUSERPOOL        MODIFY TESTRECEIVER_FAX       VARCHAR2(100);

ALTER TABLE NVUSERMAILINFO        MODIFY SENDER_NM              VARCHAR2(256);
ALTER TABLE NVUSERMAILINFO        MODIFY SENDER_EMAIL           VARCHAR2(256);
ALTER TABLE NVUSERMAILINFO        MODIFY RECEIVER_NM            VARCHAR2(256);
ALTER TABLE NVUSERMAILINFO        MODIFY SENDER_TEL             VARCHAR2(100);
ALTER TABLE NVUSERMAILINFO        MODIFY SENDER_FAX             VARCHAR2(100);
ALTER TABLE NVUSERMAILINFO        MODIFY RECEIVER_FAX           VARCHAR2(100);
ALTER TABLE NVUSERMAILINFO        MODIFY RETMAIL_RECEIVER       VARCHAR2(256);

ALTER TABLE NVREALTIMEACCEPT      MODIFY RECEIVER_NM            VARCHAR2(256);
ALTER TABLE NVREALTIMEACCEPT      MODIFY RECEIVER               VARCHAR2(256);
ALTER TABLE NVREALTIMEACCEPT      MODIFY SENDER_NM              VARCHAR2(256);
ALTER TABLE NVREALTIMEACCEPT      MODIFY SENDER                 VARCHAR2(256);

ALTER TABLE NVSCHEDULEACCEPT      MODIFY RECEIVER_NM            VARCHAR2(256);
ALTER TABLE NVSCHEDULEACCEPT      MODIFY RECEIVER               VARCHAR2(256);
ALTER TABLE NVSCHEDULEACCEPT      MODIFY SENDER_NM              VARCHAR2(256);
ALTER TABLE NVSCHEDULEACCEPT      MODIFY SENDER                 VARCHAR2(256);

ALTER TABLE NVECARELINKRESULT     MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVECARELINKRESULT     MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVECAREREJECT         MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVECAREREJECT         MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVECARERETURNMAIL     MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVECARERETURNMAIL     MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVLINKRESULT          MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVLINKRESULT          MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVREJECT              MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVREJECT              MODIFY CUSTOMER_EMAIL         VARCHAR2(256);

ALTER TABLE NVRETURNMAIL          MODIFY CUSTOMER_NM            VARCHAR2(256);
ALTER TABLE NVRETURNMAIL          MODIFY CUSTOMER_EMAIL         VARCHAR2(256);


ALTER TABLE NVFILEUPLOAD                 	MODIFY  CALL_BACK    	VARCHAR2(100);

ALTER TABLE NVECARERECEIPT            	MODIFY CUSTOMER_EMAIL     	VARCHAR2(256);
ALTER TABLE NVMIMEINFOLOG              	MODIFY CUSTOMER_EMAIL     	VARCHAR2(256);
ALTER TABLE NVRECEIPT                       	MODIFY CUSTOMER_EMAIL     	VARCHAR2(256);

ALTER TABLE NVECARERECEIPT            	MODIFY CUSTOMER_NM        	VARCHAR2(256);
ALTER TABLE NVMIMEINFOLOG              	MODIFY CUSTOMER_NM        	VARCHAR2(256);
ALTER TABLE NVRECEIPT                       	MODIFY CUSTOMER_NM        	VARCHAR2(256);

ALTER TABLE NVFILEUPLOAD                 	MODIFY CUSTOMER_SLOT1        	VARCHAR2(100);

ALTER TABLE NVFILEUPLOAD                 	MODIFY CUSTOMER_SLOT2        	VARCHAR2(100);

ALTER TABLE NVFILEUPLOAD                 	MODIFY CUSTOMER_TEL        	VARCHAR2(100);

ALTER TABLE NVSERVERINFO                 	MODIFY DBPASSWORD         	VARCHAR2(100);

ALTER TABLE NVUSER              	         	MODIFY EMAIL         	VARCHAR2(256);

ALTER TABLE NVECAREKMMAP              	MODIFY ITEM_PRAM_VALUE         	VARCHAR2(256);

ALTER TABLE NVUSERGRP                     	MODIFY MANAGER_NM         	VARCHAR2(100);

ALTER TABLE NVECARESENDLOG  MODIFY MESSAGE_KEY         	VARCHAR2(100);
ALTER TABLE NVSENDLOG        	         	MODIFY MESSAGE_KEY         	VARCHAR2(100);
ALTER TABLE NVTESTECARESENDLOG   	MODIFY MESSAGE_KEY         	VARCHAR2(100);
ALTER TABLE NVTESTSENDLOG	         	MODIFY MESSAGE_KEY         	VARCHAR2(100);

ALTER TABLE NVUSER 	         	         	MODIFY NAME_ENG         	VARCHAR2(100);

ALTER TABLE NVUSER 	         	         	MODIFY NAME_KOR         	VARCHAR2(100);

ALTER TABLE NVUSER 	         	         	MODIFY PASS_WD         	VARCHAR2(256);
ALTER TABLE NVUSERPWHISTORY MODIFY PASS_WD         	VARCHAR2(256);

ALTER TABLE NVCAMPAIGN             	MODIFY RECEIVER_NM        	VARCHAR2(256);

ALTER TABLE NVREALTIMEACCEPT     	MODIFY SECU_KEY        	VARCHAR2(100);
ALTER TABLE NVREALTIMEACCEPTDATA   MODIFY SECU_KEY        	VARCHAR2(100);
ALTER TABLE NVSCHEDULEACCEPT    	MODIFY SECU_KEY        	VARCHAR2(100);
ALTER TABLE NVSCHEDULEACCEPTDATA         	MODIFY SECU_KEY        	VARCHAR2(100);

ALTER TABLE NVCAMPAIGN                   	      	MODIFY SENDER_EMAIL        	VARCHAR2(256);
ALTER TABLE NVFILEUPLOAD                 	      	MODIFY SENDER_EMAIL        	VARCHAR2(256);

ALTER TABLE NVCAMPAIGN                   	      	MODIFY SENDER_NM        	VARCHAR2(100);
ALTER TABLE NVFILEUPLOAD                 	      	MODIFY SENDER_NM        	VARCHAR2(100);

ALTER TABLE NVCAMPAIGN                              MODIFY SENDER_TEL         	VARCHAR2(100);

ALTER TABLE NVUSER                                    	MODIFY TEL_NO         	VARCHAR2(100);

/****************************************************************
 * 기본 사용자 정보 변경 (default: Aria 사용시)
*****************************************************************/
UPDATE NVUSER
SET NAME_KOR='3EE9C92DB3C4ADA25DF79FFCBABB3107', NAME_ENG='39DD2707A7EA1A04D149DE1948A203AD', TEL_NO='9E6E05A271870D9324E4FE8D2BBDA754', EMAIL='A9551A6D2796C6D19188E66427F03B09'
WHERE USER_ID='admin';

UPDATE NVUSER
SET NAME_KOR='1226361BB6F228B307F9590BC2CA61BA', NAME_ENG='F2447C4E584FF7CF9DCA7504E3086B4C', TEL_NO='9E6E05A271870D9324E4FE8D2BBDA754', EMAIL='7E1BFAA7138628F59DCCFE56A543CE450DD3977473AA8356CE4ACBDAAF2B1FE5'
WHERE USER_ID='manager';

UPDATE NVUSER
SET NAME_KOR='71C788D06567E2DA07A89AE1E93EAFA2', NAME_ENG='D17C7DF6824BC4E6D90234ABE3948F29', TEL_NO='9E6E05A271870D9324E4FE8D2BBDA754', EMAIL='5235C0A703F7295CF0751A8AAA333C1E'
WHERE USER_ID='test';