ALTER TABLE TMB_PUSHMSG ADD SERVICE_TYPE VARCHAR(2);
ALTER TABLE TMB_PUSHMSG ADD SERVICE_NO NUMERIC(15);
ALTER TABLE TMB_PUSHMSG ADD JOB_SEQ NUMERIC(16);
ALTER TABLE TMB_PUSHMSG ADD LOG_SEND_FG VARCHAR(1) DEFAULT 'N';

CREATE INDEX TMB_PUSHMSG_SD_LSF ON TMB_PUSHMSG (SEND_DT DESC, LOG_SEND_FG ASC);
CREATE INDEX TMB_PUSHMSG_MSG_NO ON TMB_PUSHMSG (MSG_NO DESC);

ALTER TABLE TMB_PUSHMSG_RECV ADD LOG_SEND_FG VARCHAR(1) DEFAULT 'N';
CREATE INDEX TMB_PUSHMSG_RECV_LSF ON TMB_PUSHMSG_RECV (LOG_SEND_FG ASC);

ALTER TABLE TMB_PUSHMSG_OPEN ADD LOG_SEND_FG VARCHAR(1) DEFAULT 'N';
CREATE INDEX TMB_PUSHMSG_OPEN_LSF ON TMB_PUSHMSG_OPEN (LOG_SEND_FG ASC);

INSERT INTO TMB_NOTIFY_STATUS ( NOTI_TYPE, NOTI_TYPE_NM, STS_CD, UPDR_ID, UPD_DT, TTL )
VALUES ( '01', '일반', '000', 'admin', SYSDATE, 60 );
INSERT INTO TMB_NOTIFY_STATUS ( NOTI_TYPE, NOTI_TYPE_NM, STS_CD, UPDR_ID, UPD_DT, TTL )
VALUES ( '02', '정보', '000', 'admin', SYSDATE, 60 );
INSERT INTO TMB_NOTIFY_STATUS ( NOTI_TYPE, NOTI_TYPE_NM, STS_CD, UPDR_ID, UPD_DT, TTL )
VALUES ( '03', '마케팅', '000', 'admin', SYSDATE, 60 );