-- 마이스 소프트 에러코드.
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001','000','AP0001','정상','정상', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001','001','AP0001','발송대기','발송대기', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001','002','AP0001','발송대기','발송대기', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001','003','AP0001','발송대기','발송대기', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0001','010','AP0001','발송중(결과수신전)','발송중(결과수신전)', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');


INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','100','AP0004','잘못된 클라이언트 인증토큰','잘못된 클라이언트 인증토큰', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','101','AP0004','유효하지 않은 사용자 ID','유효하지 않은 사용자 ID', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','102','AP0004','잘못된 장치 토큰','잘못된 장치 토큰', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','103','AP0004','잘못된 메시지','잘못된 메시지', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','104','AP0004','잘못된 UDID','잘못된 UDID', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','105','AP0004','잘못된 버전','잘못된 버전', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','106','AP0004','잘못된 메시지 ID','잘못된 메시지 ID', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','107','AP0004','잘못된 응용 프로그램 버전','잘못된 응용 프로그램 버전', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','108','AP0004','잘못된 배지','잘못된 배지', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','109','AP0004','잘못된 모델','잘못된 모델', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','110','AP0004','잘못된 알림 정보','잘못된 알림 정보', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','111','AP0004','잘못된 이벤트 키','잘못된 이벤트 키', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','112','AP0004','유효하지 않은 이벤트 상태','유효하지 않은 이벤트 상태', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','113','AP0004','유효하지 않은 토큰 상태','유효하지 않은 토큰 상태', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','114','AP0004','유효하지 않은 알림 상태','유효하지 않은 알림 상태', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0004','120','AP0004','페이로드 생성 에러','페이로드 생성 에러', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','200','AP0002','메시지 큐 오류','메시지 큐 오류', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','300','AP0003','메시지 전송 실패','메시지 전송 실패', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','307','AP0003','너무 큰 메시지','너무 큰 메시지', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','310','AP0003','잘못된 응답 명령','잘못된 응답 명령', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','311','AP0003','오류 처리','오류 처리', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','312','AP0003','디바이스 토큰 누락','디바이스 토큰 누락', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','313','AP0003','항목 누락','항목 누락', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','314','AP0003','페이로드 누락','페이로드 누락', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','315','AP0003','유효하지 않은 토큰 크기','유효하지 않은 토큰 크기', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','316','AP0003','잘못된 항목 크기','잘못된 항목 크기', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','317','AP0003','잘못된 페이로드 크기','잘못된 페이로드 크기', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','318','AP0003','유효하지 않은 토큰','유효하지 않은 토큰', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','319','AP0003','Apns 알수없는 오류','Apns 알수없는 오류', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0003','320','AP0003','비활성 장치','비활성 장치', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','400','AP0005','메시지 전송 실패','메시지 전송 실패', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','401','AP0005','API KEY 오류','API KEY 오류', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','402','AP0005','서비스를 사용할 수 없음','서비스를 사용할 수 없음', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','403','AP0005','할당량 초과','할당량 초과', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','404','AP0005','장치 할당량 초과','장치 할당량 초과', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','405','AP0005','등록 누락','등록 누락', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','406','AP0005','잘못된 등록','잘못된 등록', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','407','AP0005','Mismatch Sender ID','Mismatch Sender ID', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','408','AP0005','등록되지 않음','등록되지 않음', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','409','AP0005','너무 큰 메시지','너무 큰 메시지', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','410','AP0005','축소 키 누락','축소 키 누락', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','411','AP0005','GCM 알수없는 오류','GCM 알수없는 오류', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','451','AP0005','CCS Connection Draining','CCS Connection Draining', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','452','AP0005','CCS 내부서버 오류','CCS 내부서버 오류', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','453','AP0005','CCS Invalid Json','CCS Invalid Json', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','454','AP0005','CCS Service Unavailable','CCS Service Unavailable', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0005','455','AP0005','CCS Bad Ack','CCS Bad Ack', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','900','AP0002','잘못된 클라이언트 인증 토큰','잘못된 클라이언트 인증 토큰', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','901','AP0002','알 수없는 OS','알 수없는 OS', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','902','AP0002','알 수없는 상태','알 수없는 상태', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','910','AP0002','알 수없는 장치 정보','알 수없는 장치 정보', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','911','AP0002','UDID 중복','UDID 중복', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','912','AP0002','메시지 풀 타임','메시지 풀 타임', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','913','AP0002','Unreceived 메시지는 존재하지 않음','Unreceived 메시지는 존재하지 않음', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','914','AP0002','알 수없는 발송 유형','알 수없는 발송 유형', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','915','AP0002','SocketException','SocketException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','916','AP0002','UnknownHostException','UnknownHostException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','917','AP0002','SocketTimeoutException','SocketTimeoutException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','918','AP0002','FileNotFoundException','FileNotFoundException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','919','AP0002','IOException','IOException', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','920','AP0002','Not Exists Config','Not Exists Config', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','921','AP0002','유효하지 않은 서버 아이디','유효하지 않은 서버 아이디', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','922','AP0002','Push 수신 거절','Push 수신 거절', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','923','AP0002','알수 없는 큐 타입','알수 없는 큐 타입', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','924','AP0002','앱 삭제','앱 삭제', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','925','AP0002','message not send','message not send', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0002','999','AP0002','기타/알수없는 오류','기타/알수없는 오류', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');

INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0101','01','AP0101','일반','일반', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0101','02','AP0101','정보','정보', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
INSERT INTO NV_CD_MST (CD_CAT, CD, PAR_CD_CAT, VAL, CD_DESC, USE_YN, REG_DTM, CD_ORD, LANG)
VALUES ('AP0101','03','AP0101','마케팅','마케팅', 'y', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') , null, 'ko');
