ALTER TABLE nvacceptsvcid               DROP PRIMARY KEY;
ALTER TABLE nvapplication               DROP PRIMARY KEY;
ALTER TABLE nvbadword                   DROP PRIMARY KEY;
ALTER TABLE nvcampaign                  DROP PRIMARY KEY;
ALTER TABLE nvcampaigninvokehistory     DROP PRIMARY KEY;
ALTER TABLE nvcamptag                   DROP PRIMARY KEY;
ALTER TABLE nvcontents                  DROP PRIMARY KEY;
ALTER TABLE nvcontentstag               DROP PRIMARY KEY;
ALTER TABLE nvcycleitem                 DROP PRIMARY KEY;
ALTER TABLE nvdbinfo                    DROP PRIMARY KEY;
ALTER TABLE nvdefaulthandler            DROP PRIMARY KEY;
ALTER TABLE nvdomainlog                 DROP PRIMARY KEY;
ALTER TABLE nvdurationinfo              DROP PRIMARY KEY;
ALTER TABLE nvecaredomainlog            DROP PRIMARY KEY;
ALTER TABLE nvecareinvokehistory        DROP PRIMARY KEY;
ALTER TABLE nvecarekmmap                DROP PRIMARY KEY;
ALTER TABLE nvecarelinkresult           DROP PRIMARY KEY;
ALTER TABLE nvecarelinktrace            DROP PRIMARY KEY;
ALTER TABLE nvecaremimeinfolog          DROP PRIMARY KEY;
ALTER TABLE nvecaremsg                  DROP PRIMARY KEY;
ALTER TABLE nvecaremsgtag               DROP PRIMARY KEY;
ALTER TABLE nvecaremultipartfile        DROP PRIMARY KEY;
ALTER TABLE nvecarereceipt              DROP PRIMARY KEY;
ALTER TABLE nvecarereject               DROP PRIMARY KEY;
ALTER TABLE nvecarereturnmail           DROP PRIMARY KEY;
ALTER TABLE nvecarerptduration          DROP PRIMARY KEY;
ALTER TABLE nvecarerptlink              DROP PRIMARY KEY;
ALTER TABLE nvecarerptopen              DROP PRIMARY KEY;
ALTER TABLE nvecarerptsendresult        DROP PRIMARY KEY;
ALTER TABLE nvecarescenario             DROP PRIMARY KEY;
ALTER TABLE nvecaresendlog              DROP PRIMARY KEY;
ALTER TABLE nvecaresendresult           DROP PRIMARY KEY;
ALTER TABLE nvecaresendresultdetail     DROP PRIMARY KEY;
ALTER TABLE nvecaretemplate             DROP PRIMARY KEY;
ALTER TABLE nvecaretraceinfo            DROP PRIMARY KEY;
ALTER TABLE nvecmschedule               DROP PRIMARY KEY;
ALTER TABLE nvecmsghandler              DROP PRIMARY KEY;
ALTER TABLE nvecmsghandlerbasic         DROP PRIMARY KEY;
ALTER TABLE nvfileupload                DROP PRIMARY KEY;
ALTER TABLE nvgrpmenurole               DROP PRIMARY KEY;
ALTER TABLE nvlinkcondition             DROP PRIMARY KEY;
ALTER TABLE nvlinkresult                DROP PRIMARY KEY;
ALTER TABLE nvlinktrace                 DROP PRIMARY KEY;
ALTER TABLE nvmenu                      DROP PRIMARY KEY;
ALTER TABLE nvmenudefaultrole           DROP PRIMARY KEY;
ALTER TABLE nvmenurole                  DROP PRIMARY KEY;
ALTER TABLE nvmenu_lang                 DROP PRIMARY KEY;
ALTER TABLE nvmimeinfolog               DROP PRIMARY KEY;
ALTER TABLE nvmobilecontents            DROP PRIMARY KEY;
ALTER TABLE nvmobilecontentstag         DROP PRIMARY KEY;
ALTER TABLE nvmultipartfile             DROP PRIMARY KEY;
ALTER TABLE nvrealtimeaccept            DROP PRIMARY KEY;
ALTER TABLE nvrealtimeacceptdata        DROP PRIMARY KEY;
ALTER TABLE nvreceipt                   DROP PRIMARY KEY;
ALTER TABLE nvreject                    DROP PRIMARY KEY;
ALTER TABLE nvreturnmail                DROP PRIMARY KEY;
ALTER TABLE nvrptduration               DROP PRIMARY KEY;
ALTER TABLE nvrptlink                   DROP PRIMARY KEY;
ALTER TABLE nvrptlinkdistinct           DROP PRIMARY KEY;
ALTER TABLE nvrptopen                   DROP PRIMARY KEY;
ALTER TABLE nvscenario                  DROP PRIMARY KEY;
ALTER TABLE nvschedule                  DROP PRIMARY KEY;
ALTER TABLE nvscheduleaccept            DROP PRIMARY KEY;
ALTER TABLE nvscheduleacceptdata        DROP PRIMARY KEY;
ALTER TABLE nvseggenealogy              DROP PRIMARY KEY;
ALTER TABLE nvsegment                   DROP PRIMARY KEY;
ALTER TABLE nvsegmentcheck              DROP PRIMARY KEY;
ALTER TABLE nvsegmenttag                DROP PRIMARY KEY;
ALTER TABLE nvsemantic                  DROP PRIMARY KEY;
ALTER TABLE nvsendblockdate             DROP PRIMARY KEY;
ALTER TABLE nvsendblockdateinfo         DROP PRIMARY KEY;
ALTER TABLE nvsendcycle                 DROP PRIMARY KEY;
ALTER TABLE nvsenderr                   DROP PRIMARY KEY;
ALTER TABLE nvsendlog                   DROP PRIMARY KEY;
ALTER TABLE nvsendresult                DROP PRIMARY KEY;
ALTER TABLE nvsendresultdetail          DROP PRIMARY KEY;
ALTER TABLE nvserverinfo                DROP PRIMARY KEY;
ALTER TABLE nvsmsrptsendresult          DROP PRIMARY KEY;
ALTER TABLE nvsmtpcategory              DROP PRIMARY KEY;
ALTER TABLE nvtemplate                  DROP PRIMARY KEY;
ALTER TABLE nvtestecaresendlog          DROP PRIMARY KEY;
ALTER TABLE nvtestsendlog               DROP PRIMARY KEY;
ALTER TABLE nvtestuser                  DROP PRIMARY KEY;
ALTER TABLE nvtestuserpool              DROP PRIMARY KEY;
ALTER TABLE nvtopdomain                 DROP PRIMARY KEY;
ALTER TABLE nvtraceinfo                 DROP PRIMARY KEY;
ALTER TABLE nvuser                      DROP PRIMARY KEY;
ALTER TABLE nvusergrp                   DROP PRIMARY KEY;
ALTER TABLE nvusermailinfo              DROP PRIMARY KEY;
ALTER TABLE nv_cd_mst                   DROP PRIMARY KEY;
ALTER TABLE nv_spam_sendlog             DROP PRIMARY KEY;
ALTER TABLE nv_status_req               DROP PRIMARY KEY;
ALTER TABLE nv_status_req_result        DROP PRIMARY KEY;
ALTER TABLE nv_svc_main                 DROP PRIMARY KEY;
ALTER TABLE nv_svc_mts                  DROP PRIMARY KEY;
ALTER TABLE nv_svc_trans                DROP PRIMARY KEY;
ALTER TABLE nv_svr_info                 DROP PRIMARY KEY;
ALTER TABLE nv_test_grp                 DROP PRIMARY KEY;
DROP INDEX idx_nvcampaign_scenario_no ON nvcampaign;
DROP INDEX idx_nvecaredomainlog_sdt_eno ON nvecaredomainlog;
DROP INDEX idx_nvecarelinkresult_ldt_eno ON nvecarelinkresult;
DROP INDEX idx_nvecarereceipt_mlt1 ON nvecarereceipt;
DROP INDEX idx_nvecarereject_rdt_eno ON nvecarereject;
DROP INDEX idx_nvecarereturnmail_rdt_eno ON nvecarereturnmail;
DROP INDEX idx_nvecarerptduration_rdt_eno ON nvecarerptduration;
DROP INDEX idx_nvecarerptlink_rdt_eno ON nvecarerptlink;
DROP INDEX idx_nvecarerptopen_rdt_eno ON nvecarerptopen;
DROP INDEX idx_nvecarerptsendresult_mlt1 ON nvecarerptsendresult;
DROP INDEX idx_nvecaresendlog_message_key ON nvecaresendlog;
DROP INDEX idx_nvecaresendlog_sdt_cky ON nvecaresendlog;
DROP INDEX idx_nvecaresendlog_sdt_cml ON nvecaresendlog;
DROP INDEX idx_nvecaresendlog_sdt_eno ON nvecaresendlog;
DROP INDEX idx_nvecaresendlog_seq ON nvecaresendlog;
DROP INDEX idx_nvecaresendresult_edt_eno ON nvecaresendresult;
DROP INDEX idx_nvecaresendresult_manubat ON nvecaresendresult;
DROP INDEX idx_nvecaresendresult_mlt1 ON nvecaresendresult;
DROP INDEX idx_nvecaresendresult_sdt_eno ON nvecaresendresult;
DROP INDEX idx_nvecaretemplatehistory_eno ON nvecaretemplatehistory;
DROP INDEX idx_nvecmsghandlerhistory_eno ON nvecmsghandlerhistory;
DROP INDEX idx_nvlinkresult_ldt_cno ON nvlinkresult;
DROP INDEX idx_nvrealtimeaccept_eno_rseq ON nvrealtimeaccept;
DROP INDEX idx_nvrealtimeaccept_req_dt ON nvrealtimeaccept;
DROP INDEX idx_nvrealtimeaccept_send_fg ON nvrealtimeaccept;
DROP INDEX idx_nvreceipt_odt_cno ON nvreceipt;
DROP INDEX idx_nvreject_rdt_cno ON nvreject;
DROP INDEX idx_nvreturnmail_rdt_cno ON nvreturnmail;
DROP INDEX idx_nvrptduration_report_dt ON nvrptduration;
DROP INDEX idx_nvrptlinkdistinct_rpt_dt ON nvrptlinkdistinct;
DROP INDEX idx_nvrptlink_rdt_cno ON nvrptlink;
DROP INDEX idx_nvrptopen_report_dt ON nvrptopen;
DROP INDEX idx_nvscheduleaccept_req_dt ON nvscheduleaccept;
DROP INDEX idx_nvscheduleaccept_send_fg ON nvscheduleaccept;
DROP INDEX idx_nvsendlog_cno_ecd ON nvsendlog;
DROP INDEX idx_nvsendlog_message_key ON nvsendlog;
DROP INDEX idx_nvsendlog_sdt_cky ON nvsendlog;
DROP INDEX idx_nvsendlog_sdt_cml ON nvsendlog;
DROP INDEX idx_nvsendlog_seq ON nvsendlog;
DROP INDEX idx_nvsmsrptsendresult_sno_rsq ON nvsmsrptsendresult;
DROP INDEX idx_nvsmsrptsendresult_sno_sgb ON nvsmsrptsendresult;
DROP INDEX idx_nvsmsrptsendresult_sno_stp ON nvsmsrptsendresult;
DROP INDEX idx_nvtestecaresendlog_send_dt ON nvtestecaresendlog;
DROP INDEX idx_nvtestsendlog_send_dt ON nvtestsendlog;
DROP INDEX idx_nv_cd_mst_par_cd_cat ON nv_cd_mst;