alter table nvapplication add constraint fk_campaign_application foreign key (campaign_no) references nvcampaign (campaign_no);
alter table nvcampaign add constraint fk_segment_campaign foreign key (segment_no) references nvsegment (segment_no);
alter table nvcampaign add constraint fk_usergrp_campaign foreign key (grp_cd) references nvusergrp (grp_cd);
alter table nvcampaign add constraint fk_user_campaign foreign key (user_id) references nvuser (user_id);
alter table nvcontents add constraint fk_usergrp_contents foreign key (grp_cd) references nvusergrp (grp_cd);
alter table nvcontents add constraint fk_user_contents foreign key (user_id) references nvuser (user_id);
alter table nvcycleitem add constraint fk_ecmschedule_cycleitem foreign key (ecmschedule_no) references nvecmschedule (ecmschedule_no);
alter table nvdomainlog add constraint fk_senderr_domainlog foreign key (error_cd) references nvsenderr (error_cd);
alter table nvdomainlog add constraint fk_sendresult_domainlog foreign key (campaign_no, result_seq) references nvsendresult (campaign_no, result_seq);
alter table nvecaredomainlog add constraint fk_senderr_ecaredomainlog foreign key (error_cd) references nvsenderr (error_cd);
alter table nvecarekmmap add constraint fk_usergrp_ecarekmmap foreign key (grp_cd) references nvusergrp (grp_cd);
alter table nvecarekmmap add constraint fk_user_ecarekmmap foreign key (user_id) references nvuser (user_id);
alter table nvecarelinkresult add constraint fk_elt_ecarelinkresult foreign key (ecare_no, link_seq) references nvecarelinktrace (ecare_no, link_seq);
alter table nvecarelinkresult add constraint fk_esr_ecarelinkresult foreign key (ecare_no, result_seq) references nvecaresendresult (ecare_no, result_seq);
alter table nvecarelinktrace add constraint fk_ecaremsg_ecarelinktrace foreign key (ecare_no) references nvecaremsg (ecare_no);
alter table nvecaremsg add constraint fk_segment_ecaremsg foreign key (segment_no) references nvsegment (segment_no);
alter table nvecaremsg add constraint fk_usergrp_ecaremsg foreign key (grp_cd) references nvusergrp (grp_cd);
alter table nvecaremsg add constraint fk_user_ecaremsg foreign key (user_id) references nvuser (user_id);
alter table nvecaremultipartfile add constraint fk_nvecaremsg_file foreign key (ecare_no) references nvecaremsg (ecare_no);
alter table nvecarereceipt add constraint fk_esr_ecarereceipt foreign key (ecare_no, result_seq) references nvecaresendresult (ecare_no, result_seq);
alter table nvecarereject add constraint fk_esr_ecarereject foreign key (ecare_no, result_seq) references nvecaresendresult (ecare_no, result_seq);
alter table nvecarereturnmail add constraint fk_esr_ecarereturnmail foreign key (ecare_no, result_seq) references nvecaresendresult (ecare_no, result_seq);
alter table nvecarerptlink add constraint fk_elt_ecarerptlink foreign key (ecare_no, link_seq) references nvecarelinktrace (ecare_no, link_seq);
alter table nvecaresendlog add constraint fk_esr_ecaresendlog foreign key (ecare_no, result_seq) references nvecaresendresult (ecare_no, result_seq);
alter table nvecaresendresult add constraint fk_ecaremsg_ecaresendresult foreign key (ecare_no) references nvecaremsg (ecare_no);
alter table nvecaretemplate add constraint fk_ecaremsg_ecaretemplate foreign key (ecare_no) references nvecaremsg (ecare_no);
alter table nvecaretraceinfo add constraint fk_ecaremsg_ecaretraceinfo foreign key (ecare_no) references nvecaremsg (ecare_no);
alter table nvecmschedule add constraint fk_sendcycle_ecmschedule foreign key (cycle_cd) references nvsendcycle (cycle_cd);
alter table nvecmsghandler add constraint fk_ecaremsg_ecmsghandler foreign key (ecare_no) references nvecaremsg (ecare_no);
alter table nvlinkcondition add constraint fk_schedule_linkcondition foreign key (scenario_no, schedule_seq) references nvschedule (scenario_no, schedule_seq);
alter table nvlinkresult add constraint fk_linktrace_linkresult foreign key (campaign_no, link_seq) references nvlinktrace (campaign_no, link_seq);
alter table nvlinktrace add constraint fk_campaign_linktrace foreign key (campaign_no) references nvcampaign (campaign_no);
alter table nvmultipartfile add constraint fk_campaign_multipartfile foreign key (campaign_no) references nvcampaign (campaign_no);
alter table nvreceipt add constraint fk_sendresult_receipt foreign key (campaign_no, result_seq) references nvsendresult (campaign_no, result_seq);
alter table nvreject add constraint fk_sendresult_reject foreign key (campaign_no, result_seq) references nvsendresult (campaign_no, result_seq);
ALTER TABLE nvreturnmail ADD CONSTRAINT fk_sendresult_returnmail FOREIGN KEY (campaign_no, result_seq) REFERENCES nvsendresult (campaign_no, result_seq);
ALTER TABLE nvrptduration ADD CONSTRAINT fk_campaign_rptduration FOREIGN KEY (campaign_no) REFERENCES nvcampaign (campaign_no);
ALTER TABLE nvrptlink ADD CONSTRAINT fk_linktrace_rptlink FOREIGN KEY (campaign_no, link_seq) REFERENCES nvlinktrace (campaign_no, link_seq);
ALTER TABLE nvrptopen ADD CONSTRAINT fk_campaign_rptopen FOREIGN KEY (campaign_no) REFERENCES nvcampaign (campaign_no);
ALTER TABLE nvscenario ADD CONSTRAINT fk_usergrp_scenario FOREIGN KEY (grp_cd) REFERENCES nvusergrp (grp_cd);
ALTER TABLE nvscenario ADD CONSTRAINT fk_user_scenario FOREIGN KEY (user_id) REFERENCES nvuser (user_id);
ALTER TABLE nvschedule ADD CONSTRAINT fk_campaign_schedule FOREIGN KEY (campaign_no) REFERENCES nvcampaign (campaign_no);
ALTER TABLE nvschedule ADD CONSTRAINT fk_scenario_schedule FOREIGN KEY (scenario_no) REFERENCES nvscenario (scenario_no);
ALTER TABLE nvseggenealogy ADD CONSTRAINT fk_segment_seggenealogy FOREIGN KEY (segment_no) REFERENCES nvsegment (segment_no);
ALTER TABLE nvsegment ADD CONSTRAINT fk_dbinfo_segment FOREIGN KEY (dbinfo_seq) REFERENCES nvdbinfo (dbinfo_seq);
ALTER TABLE nvsegment ADD CONSTRAINT fk_usergrp_segment FOREIGN KEY (grp_cd) REFERENCES nvusergrp (grp_cd);
ALTER TABLE nvsegment ADD CONSTRAINT fk_user_segment FOREIGN KEY (user_id) REFERENCES nvuser (user_id);
ALTER TABLE nvsemantic ADD CONSTRAINT fk_segment_semantic FOREIGN KEY (segment_no) REFERENCES nvsegment (segment_no);
ALTER TABLE nvsenderr ADD CONSTRAINT fk_smtpcategory_senderr FOREIGN KEY (category_cd) REFERENCES nvsmtpcategory (category_cd);
ALTER TABLE nvsendresult ADD CONSTRAINT fk_campaign_sendresult FOREIGN KEY (campaign_no) REFERENCES nvcampaign (campaign_no);
ALTER TABLE nvtemplate ADD CONSTRAINT fk_campaign_template FOREIGN KEY (campaign_no) REFERENCES nvcampaign (campaign_no);
ALTER TABLE nvtestuserpool ADD CONSTRAINT fk_user_testuserpool FOREIGN KEY (user_id) REFERENCES nvuser (user_id);
ALTER TABLE nvtraceinfo ADD CONSTRAINT fk_campaign_traceinfo FOREIGN KEY (campaign_no) REFERENCES nvcampaign (campaign_no);
ALTER TABLE nvuser ADD CONSTRAINT fk_usergrp_user FOREIGN KEY (grp_cd) REFERENCES nvusergrp (grp_cd);
ALTER TABLE nvusermailinfo ADD CONSTRAINT fk_user_usermailinfo FOREIGN KEY (user_id) REFERENCES nvuser (user_id);